### ISSUE TITLE
ReadTheDocs text not match .rst file

### ISSUE THREAD

**Issue by danijeljw** [tweepy/tweepy#1005]
When I was reading the Tweepy docs here: http://docs.tweepy.org/en/v3.5.0/streaming_how_to.html

I came across the following code:

```python
myStreamListener = MyStreamListener()
myStream = tweepy.Stream(auth = api.auth, listener=myStreamListener())
```

as shown here:

![text in .rst not matches RTD][image]

But when I went to check the .RST file on GitHub, it's showing accurately as it should:

```python
myStreamListener = MyStreamListener()
myStream = tweepy.Stream(auth = api.auth, listener=myStreamListener)
```

The parenthesis pair at the end of the **myStreamListener** should not be there, as it's shown in the docs.

Why is ReadTheDocs showing this with a pair of parenthesis?

[image]: https://i.imgur.com/3Vp3ABb.png

**Comment by Harmon758** [comment]
This is because this was fixed in https://github.com/tweepy/tweepy/commit/8322cf6252db66c2288fdbf6c218f88518320cb9 after v3.5.0 was released.
You're looking at the [documentation for v3.5.0](https://github.com/tweepy/tweepy/blob/v3.5.0/docs/streaming_how_to.rst).
You should refer to http://docs.tweepy.org/en/latest/streaming_how_to.html instead for the latest documentation or http://docs.tweepy.org/en/stable/streaming_how_to.html (equivalent to [3.7.0](http://docs.tweepy.org/en/3.7.0/streaming_how_to.html) right now) for the documentation for the latest release.
As for changing the Default version for Read the Docs to avoid this confusion, see #1134.

**Comment by danijeljw** [comment]
Thanks for the update. :-)
