### ISSUE TITLE
Tweepy media upload unsuccesful

### ISSUE THREAD

**Issue by new-yen** [tweepy/tweepy#1020]
Hello,

I am quite new to coding and got a bit stuck on this. I have been trying to use tweepy to upload a Image/GIF, unfortunately without any success so far. Please see the code I used below:

`import tweepy
import json

with open('twitterauth.json') as file:
      secrets = json.load(file)
      
auth = tweepy.OAuthHandler(secrets['consumer_key'], secrets['consumer_secret'])
auth.set_access_token(secrets['access_token'], secrets['access_token_secret'])

twitter = tweepy.API(auth)

twitter.update_with_media('/home/pi/gifcam/gifs/test_1.jpg', 'your status update')`

I was able to make a tweet but no luck with Image/GIF.

Every help would be much appreciated.

Thanks and best regards
david

**Comment by moghya** [comment]
@new-yen
This is because [POST statuses/update_with_media is now Deprecated]() we have to change the working of  `update_with_media` [here](https://github.com/tweepy/tweepy/blob/8373a0ab040461531c26076693cc99ecd2a7c3f1/tweepy/api.py#L214) and make it work as specified [here](https://developer.twitter.com/en/docs/media/upload-media/overview).

@Aaron1011 @joshthecoder  I can fix it, please assign it to me. Thanks.

**Comment by new-yen** [comment]
@moghya thanks for the information. The missing chunked upload might still lead to problems with bigger file sizes,which was not an issue in my case, as I only tried to upload small images and GIFs.

I figured out, that my problem was, that I tried running my script in Python 3 but it only works in Python 2.

I think this is worth mentioning and maybe should go in a pull request or did I just miss this information somehow.

Thanks and best regards
david

**Comment by Harmon758** [comment]
[POST statuses/update_with_media](https://web.archive.org/web/20190809210259/https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update_with_media), the endpoint that [`API.update_with_media`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_with_media) uses, has indeed been deprecated and is no longer documented now. You should use [`API.media_upload`](https://tweepy.readthedocs.io/en/latest/api.html#API.media_upload) with [`API.update_status`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_status) instead. See [Twitter's API documentation for uploading media](https://developer.twitter.com/en/docs/media/upload-media/overview).

See also the documentation for the `in_reply_to_status_id` parameter of `API.update_with_media` and `API.update_status`.

Tweepy should be fully compatible with Python 3. Without a full traceback or a reproducible example (MCVE/SSCCE), it's impossible to determine what exactly your issue is, although you're uploading a file with a `.jpg` extension even though your issue specifies that you're uploading a GIF.

As for chunked uploads, see #929.

For code block usage, see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
