### ISSUE TITLE
Streaming api make some requests during time interval

### ISSUE THREAD

**Issue by AlexProfi** [tweepy/tweepy#1023]
I want to send requests by rest api when stream is working for example in keep_alive method
to get people who unfollow tweets or delete replies.
In the python-twitter package it sends keep alive signals at setting period
But here there is no such signals
How make this logic?

**Comment by Harmon758** [comment]
I'm not sure I understand your use case, but you can use the event functions of the stream listener, e.g. `on_status`, to process each status, etc. Alternatively, you can use the `is_async` parameter of `Stream.filter` to run the stream asynchronously, so that you can execute whatever you'd like afterwards, outside the stream listener.
