### ISSUE TITLE
Catch Rate Limit

### ISSUE THREAD

**Issue by nathan30** [tweepy/tweepy#1034]
Hi,

I begin in the Tweepy dev' and have a little question. Here is my authentification : 

`    api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True, compression=True)`

I have an error message saying "Rate limit reached. Sleeping for: XXX". But I want to know if it's possible to catch the RateLimit error in order to log it into a specified log file ?

Thanks in advance

**Comment by Harmon758** [comment]
That "error message" is actually a log warning from the "tweepy.binder" logger:
https://github.com/tweepy/tweepy/blob/cf172c6923cb019734a10f54f8a2d530658326a8/tweepy/binder.py#L20 https://github.com/tweepy/tweepy/blob/cf172c6923cb019734a10f54f8a2d530658326a8/tweepy/binder.py#L160  You can simply add a handler to that logger to output it to the file that you want or configure the root logger to do so.

Otherwise, you'll have to set `wait_on_rate_limit` to `False` (or not specify the parameter at all since the default is `False`) to actually catch and handle the `RateLimitError`.
