### ISSUE TITLE
Target user not specified error

### ISSUE THREAD

**Issue by ahoora08** [tweepy/tweepy#1052]
When I try to call some methods like ‍‍_show_friendship_ I got the error
```
raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{u'message': u'Target user not specified.', u'code': 164}].
```

Here is my complete code:
```
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)
status = api.show_friendship("A", "B")
```
while I can use some other methods like get_user.

- Tweepy version 3.6.0

- python 2.7

**Comment by do-n-khanh** [comment]
same problem, except that I use 2.3.0

**Comment by do-n-khanh** [comment]
hello, can anybody help me to solve this problem?

**Comment by Harmon758** [comment]
Since inputs could be either IDs or screen names, [`API.show_friendship`](https://tweepy.readthedocs.io/en/latest/api.html#API.show_friendship) doesn't accept positional parameters, so when using the method, you need to specify which one it is via keyword arguments, e.g. `api.show_friendship(source_screen_name="A", target_screen_name="B")`.
