### ISSUE TITLE
Tweet.py search method does not support pagination for tweets view

### ISSUE THREAD

**Issue by syednh110** [tweepy/tweepy#1079]
I was reading over the pagination docs and it sounds great. From the tweetpy documentation page is a supported parameter. Am I doing something incorrect when I expect this behavior to work?

for status in tweepy.Cursor(api.get_user('AliNamdar10')).items(20):
    # Process a single status
    print(status.text)

**Comment by mdangschat** [comment]
I was also interested in this. However according to [Twitter's API documentation](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html) the `rpp` and `page` parameters have been replaced by `count`.

> count | optional | The number of tweets to return per page, up to a maximum of 100.  Defaults to 15. This was formerly the "rpp" parameter in the old Search  API.

So, the [Tweepy documentation](https://tweepy.readthedocs.io/en/v3.5.0/api.html#help-methods) needs an update.

**Comment by Harmon758** [comment]
@syednh110: [`API.get_user`](http://docs.tweepy.org/en/latest/api.html#API.get_user) returns a single `User` object, so there is nothing to paginate.

@mdangschat:
This does not relate to this issue and has already been updated with https://github.com/tweepy/tweepy/commit/5bd7431166a5714c0474aa69ee9f327095c3ccba / https://github.com/tweepy/tweepy/commit/069f688c1cfdb60605274c69bd1a9724732c845d (#1165).
The documentation simply hasn't been built yet since then: https://readthedocs.org/projects/tweepy/builds/
I believe @joshthecoder might have to trigger a build manually.
Once it is built, the update will be reflected at http://docs.tweepy.org/en/latest/api.html#API.search and https://tweepy.readthedocs.io/en/latest/api.html#API.search.
