### ISSUE TITLE
Direct Message API changes

### ISSUE THREAD

**Issue by j-e-d** [tweepy/tweepy#1081]
Twitter is deprecating some of it's REST API endpoints for Direct Messages on August 16, 2018 and replacing them with new endpoints that require changes in how data is sent, they will also return DMs with a different format. More details in the [Direct Message Migration](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/direct-message-migration) guide and in the [announcement](https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736).

Edit: new reminder from twitter: https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482

**Comment by do-n-khanh** [comment]
twitter is going to shut down Direct Message API today. Is there any update? Thanks.

**Comment by j-e-d** [comment]
Update from Twiiter:
>The legacy Direct Message endpoints will flicker periodically for one month. At the end of that period, on September 17, requests to them will return errors. During the flicker period, we will also return 404 error messages. We will share details about the flickering schedule for these DM endpoints here on the forums soon.

 https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746

**Comment by do-n-khanh** [comment]
Because I just need to send direct message, where is a quick fix for anyone who wants it right now:
https://github.com/do-n-khanh/tweepy/blob/patch-1/tweepy/api.py

You can send DM like:

    event = {
      "event": {
        "type": "message_create",
        "message_create": {
          "target": {
            "recipient_id": 'user_id'
          },
          "message_data": {
            "text": 'This is a test'
          }
        }
      }
    }
    api.send_direct_message_new(event)

**Comment by do-n-khanh** [comment]
@StefTocup: Sorry, my version is 2.3.0. Let's me see how it works in 3.6.0

**Comment by do-n-khanh** [comment]
@StefTocup: I made a dirty fix to make it work in 3.6.0 by adding 3 lines of code to binder.py
 
https://github.com/do-n-khanh/tweepy/commit/c978749edb944394bd412922d0eb30170e0598bf

Let's me know if it works for you.

**Comment by StefTocup** [comment]
@do-n-khanh it's working with this quick fix.
But using screen name no longer work, I had to search for id using :
```
user = self.api.get_user(self.destname)
self.dest_id = user.id
```

**Comment by do-n-khanh** [comment]
yes, it is because twitter api only allow user id.

**Comment by ZeroCoolHacker** [comment]
It is not working.

**Comment by arturoabruzzini** [comment]
Hi, has anyone picked this up? Do we have an idea of when Tweepy will be migrated to the new API?

**Comment by do-n-khanh** [comment]
> It is not working.

Please paste the error log.

**Comment by Exceen** [comment]
I'm using tweepy 3.6.0 and it doesn't work for me either. I added the lines from your commit https://github.com/do-n-khanh/tweepy/commit/c978749edb944394bd412922d0eb30170e0598bf and noticed that the path seems to be `/direct_messages/new.json` and not `/direct_messages/events/new.json`. I corrected this but I still get the same error message.

Printing `args` gives `(u'Exceen_',)` and `kwargs` gives `{'text': u'@priyapsingh84 and @mmx05202147 followed you.'}`

`
Traceback (most recent call last):
  File "/usr/local/bin/followings", line 80, in <module>
    main()
  File "/usr/local/bin/followings", line 62, in main
    notify_via_dm(followings, api_bot, '%s followed you.', new_followers)
  File "/usr/local/bin/followings", line 73, in notify_via_dm
    response = api.send_direct_message(recipient, text=message)
  File "/home/pi/.local/lib/python2.7/site-packages/tweepy/binder.py", line 257, in _call
    return method.execute()
  File "/home/pi/.local/lib/python2.7/site-packages/tweepy/binder.py", line 241, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{u'message': u'Sorry, that page does not exist.', u'code': 34}]
`

What I don't understand is how this should fix the problem. You're essentially removing the two important arguments to send a DM. But then again I didn't look into tweepy's code so I have 0 understanding of what tweepy does. I just seems quite weird and looks like you're not just preventing the error message but also the DM from being sent.

**Comment by Exceen** [comment]
@do-n-khanh 
Your v2.3.0 fix adds two new methods. One of them calls the other but the first one is never called, at least on v3.6.0.

That is the problem here. I didn't figure out what the `messageobject` is supposed to be tho.

**Comment by Exceen** [comment]
Looking further into your code you even have some syntax errors there... also I don't get it how this fix is supposed to work for you. It must throw you tons of errors, no matter which version tweepy or python you use.

Gonna work on my own solution as soon as I have time for this.

**Comment by bakayim** [comment]
I fixed "get" part of DM. Waiting my pull request to be merged

You can find pull request at: [#1109](https://github.com/tweepy/tweepy/pull/1109)
You can use my forked repo: [https://github.com/bakayim/tweepy](https://github.com/bakayim/tweepy)

**Comment by do-n-khanh** [comment]
what framework or environment are you working on? you need to make sure that the modified tweepy lib is called instead of the old one.

and please make sure 2 methods are put in api.py file. 

lastly, you need to paste the error log so that i can figure out the error.

**Comment by FdMon** [comment]
do-n-khanh, your point. I had changed a old lib....

now it works fine!!!  thanks a lot!!!

**Comment by huangweibuct** [comment]
Hi do-nkhanh,

Have you met this error: "tweepy.error.TweepError: [{u'message': u'You cannot send messages to users who are not following you.', u'code': 150}]"

I wanted to use send_direct_message_new to send message to some users who is not following me and whom I'm not following too. 

Any ideas?

Thanks!

**Comment by do-n-khanh** [comment]
that is impossible due to twitter rules

**Comment by martynfielding** [comment]
> https://github.com/bakayim/tweepy

Thanks for this.

**Comment by Dixit22** [comment]
I had to apply the above fixes ( https://github.com/tweepy/tweepy/issues/1081#issuecomment-423486837 ) to get version 3.7.0 to work.  That was the version `pip install tweepy` gave me on 28-Dec and  I was a bit surprised such a new version didn't already include them.

**Comment by lshaf** [comment]
Do I need to fetch it manually from bind_api?
I'm using version 3.7.0 and can't fetch DM due to outdated urls

https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference

**Comment by machine-uprising** [comment]
I'm working on a fork of tweepy to update the direct message endpoints as well as adding the new functionality of quick replies, buttons and the async media upload that is now required for direct messages. I'm also working on including the new Welcome Message endpoints and Welcome Message Rules. There's been a fair bit of work involved in this and it's a pretty significant update as it affects multiple files in tweepy (api, binder, cursor, models, parsers), adds a new file (mediaasync.py) that is a modified version of binder.py for the async media uploader. These updates also add to some of the key design methodology on which tweepy operates in api.py and binder.py. The cursor styles for direct messages and welcome messages are also different to the standard cursor method used by the API which adds further complexity to the updates. 

You can find the fork I'm working on here https://github.com/machine-uprising/tweepy/tree/direct_messages 
The working branch in this repository is the 'direct_messages' branch but both branches (master and direct_messages) are being updated with recent pull requests from the tweepy master branch that @Harmon758 has been updating. 

To keep track of the changes made for documentation and for testing I have a wiki setup in this repository - https://github.com/machine-uprising/tweepy-devtest/wiki The wiki has details about the updates being made and examples for testing/using the new endpoints. 

This would be a pretty major pull request. Also, because of the changes required the Travis CI tests are failing on the new endpoints of direct messages and will likely require rerecording the cassettes. This would need input from @Harmon758 and/or @joshthecoder 

If anyone wants to setup their own virtual environment and run some testing that would be a great help.

**Comment by pedrodejesus** [comment]
Hi, I'm using 3.7.0 and DM methods are still not working. There are any ways to get it fixed?

**Comment by Harmon758** [comment]
I've now made a branch (https://github.com/tweepy/tweepy/tree/dm-migration) and draft PR (#1228) for the Direct Message migration. It should fully support the new changes.
Feel free to test it and report any issues you encounter.

@huangweibuct This is not something that Twitter allows and is consistent with the website/app.
See https://help.twitter.com/en/using-twitter/direct-messages.

@machine-uprising #1228 simply restores basic DM functionality.
Feel free to PR specific additional features.
Although, your fork seems to be an amalgamation of various changes and I would recommend splitting each component into a separate PR so that it's easier to review and merge.
