### ISSUE TITLE
Using tweet_mode='extended'. Charmap Error?

### ISSUE THREAD

**Issue by OliMations** [tweepy/tweepy#1125]
So I am using some code which i downloaded. That all works fine. But i want to edit it slightly to allow the longer tweets. But when i try it just gives me an error?

```python
def get_tweets(username):
	auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
	auth.set_access_token(access_key, access_secret)
	api = tweepy.API(auth)
	number_of_tweets = 200

	tweets = api.user_timeline(screen_name = username,count = number_of_tweets,tweet_mode='extended')

	tweets_for_csv = [[tweet.created_at, tweet.full_text] for tweet in tweets]
                
	with open("{0}_tweets.csv".format(username) , 'w+') as file:
		writer = csv.writer(file, delimiter='.')
		writer.writerows(tweets_for_csv)```

This causes the error:
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 23-26: character maps to <undefined>

**Comment by Harmon758** [comment]
This is an error with your encoding rather than an issue with Tweepy.
The default encoding for [`open`](https://docs.python.org/3/library/functions.html#open) is platform dependent.
One of the Tweets you're processing is using characters that your default encoding doesn't support.
This should easily be resolved by setting the encoding keyword argument to UTF-8 when opening the file.

**Comment by PandaWhoCodes** [comment]
try doin this
```
	with open("{0}_tweets.csv".format(username) , 'w+',encoding="utf-8") as file:
		writer = csv.writer(file, delimiter='.')
		writer.writerows(tweets_for_csv)

```
