### ISSUE TITLE
I am not able to get the expanded url from tweepy , the tweets which are tweeted from android app

### ISSUE THREAD

**Issue by billyurs** [tweepy/tweepy#1156]
I have just tweeted from my android app, #cinetestloop it is just tweet.

But in tweepy I am not able to get expanded url.

Even I have tried with tweet_mode=extended

{"full_text": "#cinetestloop it is just tweet", "in_reply_to_user_id": null, "favorite_count": 0, "created_at": "Mon Jan 21 05:36:08 +0000 2019", "source": "<a href=\\"http://twitter.com/download/android\\" rel=\\"nofollow\\">Twitter for Android</a>", "id": 1087222289991520256, "metadata": {"result_type": "recent", "iso_language_code": "en"}, "retweet_count": 0, "id_str": "1087222289991520256", "in_reply_to_status_id_str": null, "coordinates": null, "in_reply_to_user_id_str": null, "contributors": null, "place": null, "lang": "en", "entities": {"urls": [], "symbols": [], "hashtags": [{"indices": [0, 13], "text": "cinetestloop"}], "user_mentions": []}, "favorited": false, "retweeted": false, "user": {"profile_link_color": "1DA1F2", "translator_type": "none", "geo_enabled": false, "created_at": "Tue Jan 26 15:44:56 +0000 2016", "is_translation_enabled": false, "following": false, "id": 4817274554, "protected": false, "notifications": false, "friends_count": 95, "description": "Full stack developer(Python Django with Angular js) and Short Film maker", "profile_text_color": "333333", "id_str": "4817274554", "profile_image_url": "http://pbs.twimg.com/profile_images/965101636157718528/QrIz52ls_normal.jpg", "url": null, "profile_banner_url": "https://pbs.twimg.com/profile_banners/4817274554/1503397553", "is_translator": false, "screen_name": "Madhusudanbilly", "name": "Madhusudan", "listed_count": 1, "default_profile_image": false, "contributors_enabled": false, "profile_use_background_image": true, "has_extended_profile": true, "lang": "en", "followers_count": 37, "entities": {"description": {"urls": []}}, "profile_background_image_url": null, "utc_offset": null, "time_zone": null, "profile_background_image_url_https": null, "favourites_count": 479, "profile_background_color": "F5F8FA", "verified": false, "profile_background_tile": false, "profile_sidebar_fill_color": "DDEEF6", "follow_request_sent": false, "default_profile": true, "profile_sidebar_border_color": "C0DEED", "profile_image_url_https": "https://pbs.twimg.com/profile_images/965101636157718528/QrIz52ls_normal.jpg", "statuses_count": 305, "location": "Bengaluru, India"}, "is_quote_status": false, "in_reply_to_status_id": null, "display_text_range": [0, 30], "in_reply_to_screen_name": null, "truncated": false, "geo": null}

**Comment by Harmon758** [comment]
I'm not sure what you mean by "expanded url".
If you're trying to get the URL of the Tweet from the object, you can do so by using its ID and the user's name, e.g. `f"https://twitter.com/{tweet['user']['name']}/status/{tweet['id']}"`.
In your example, it would be https://twitter.com/Madhusudanbilly/status/1087222289991520256
If you're trying to generate a link for the hashtag, you can do so using the entity, e.g. `f"https://twitter.com/hashtag/{tweet['entities']['hashtags'][0]['text']}"`.
Otherwise, this example Tweet doesn't have any links in it.
If it did, `expanded_url` would be a key in the [URL objects/entities](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#urls).

**Comment by billyurs** [comment]
Thanks for the reply, issue solved
