### ISSUE TITLE
cant install tweepy on anaconda 3.7

### ISSUE THREAD

**Issue by achzain12** [tweepy/tweepy#1159]
Hello,

I try to install tweepy to my anaconda :

conda install -c conda-forge/label/cf201901 tweepy 

but the result :

Solving environment : /

and when i try to find that package  with :

conda search tweepy 

the result :

Loading channels: done

PackagesNotFoundError: The following packages are not available from current channels:

  - tweepy

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by Harmon758** [comment]
Based on [the documentation](https://github.com/conda-forge/tweepy-feedstock/blob/master/README.md#installing-tweepy), I think you need to specify the channel in the search.
i.e. `conda search tweepy --channel conda-forge`.
As for stalling on `Solving environment`, that seems to be an issue with Conda rather than with Tweepy.
See https://github.com/conda/conda/issues/6406, https://github.com/conda/conda/issues/7690, https://github.com/conda/conda/issues/8051, https://github.com/conda/conda/issues/8116, etc.
or search for "Conda stuck Solving environment" for other potential solutions.

**Comment by achzain12** [comment]
thank you for your reply.

Now I try to install tweepy package to anaconda using :

conda install --override-channel -c main -c conda-forge tweepy

but the result :

Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:

scikit-image
tweepy
Use "conda info " to see the dependencies for each package.

**Comment by Harmon758** [comment]
This is likely an issue with your environment, but I don't think Tweepy and scikit-image even have any overlapping requirements, so it could be an issue with Conda as well.
But again, this isn't an issue with Tweepy, and this isn't the right place to request help with Conda.
A simple search for the error will return numerous results outlining potential underlying causes and solutions.

**Comment by achzain12** [comment]
Ok thank you for your help.
:)

**Comment by hannaariniparhusip** [comment]
What is the conclusion for above problem ? I have the same problem
