### ISSUE TITLE
api.retweets function returns a list of the same status

### ISSUE THREAD

**Issue by PakanAngel** [tweepy/tweepy#1161]
I need to retrieve all retweets of a given tweet by using api.retweets function. 
But the result is a list of the same status object. 
```
retweets = api.retweets(1085265146644058112,100)
for retweet in retweets:
    print retweet._json["retweeted_status"]["text"] +"\n\n\n"
    outputFile.write(retweet._json["retweeted_status"]["text"] +"\n")
    count +=1
```
Is there anyway to get the text of the retweets?

**Comment by Harmon758** [comment]
This is not the case.
You're printing and writing the text of the retweeted status of each retweet. That's going to be the same since they're all retweets of the same Tweet, so you're just printing and writing the text of the original Tweet.

**Comment by PakanAngel** [comment]
Right. But how can I get the quotes's text.

**Comment by Harmon758** [comment]
I'm not sure what you mean by "the quote".
You're already getting the text of the original Tweet. You can also do this more easily by using [`API.get_status`](http://docs.tweepy.org/en/latest/api.html#API.get_status) and getting the Tweet object directly instead of getting Retweets and getting the original Tweet from a Retweet.
Also, [`API.retweets`](http://docs.tweepy.org/en/latest/api.html#API.retweets) returns a list of Status objects, so instead of accessing the internal JSON dictionary directly, you can just use the attributes of the object. This also applies to the text of the Retweeted status, since the `retweeted_status` attribute returns a Status object itself.

**Comment by PakanAngel** [comment]
Thanks
