### ISSUE TITLE
UNTIL PARAMETER NOT WORKING

### ISSUE THREAD

**Issue by rsrija** [tweepy/tweepy#1162]
I am using since and until in my program. When i use only since, My program retreives the data.But when i use until parameter, my program will not execute and retuurns exit code0

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)

csvFile = open('piano.csv', 'a')

csvWriter = csv.writer(csvFile)

for tweet in tweepy.Cursor(api.search, q="#piano", lang="en", since="2018-07-07" , until="2018-12-12").items(99999):

    print (tweet.created_at, tweet.text, tweet.retweet_count, tweet.id_str,tweet.user.name,tweet.user.id_str)
    csvWriter.writerow([tweet.created_at, tweet.text.encode('utf8'),tweet.retweet_count,tweet.id_str.encode('utf-8'),tweet.user.name.encode('utf-8'),tweet.user.id_str.encode('utf-8')])

![capture](https://user-images.githubusercontent.com/15873305/51613551-aa322f00-1f49-11e9-8d0f-13fd893a0aff.PNG)

**Comment by Harmon758** [comment]
The `until` parameter is functioning properly.

Per the [documentation of Twitter's search endpoint](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators):
> The Search API is not a complete index of all Tweets, but instead an index of recent Tweets. The index includes between 6-9 days of Tweets.

and [of the `until` parameter](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html):

> Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.

As 2018-12-12 is more than 7-9 days ago, your search is returning no results.
Your program therefore attempts to loop through an empty list, prints and writes nothing since it never enters the loop, and then returns with an exit code of 0, meaning it successfully completed.

**Comment by rsrija** [comment]
thankyou. But then, how can I do that work?

**Comment by Harmon758** [comment]
I'm not sure what you're asking.
To search Tweets older than that limit, you'll have to use the [premium search APIs](https://developer.twitter.com/en/docs/tweets/search/overview/premium).
