### ISSUE TITLE
only one row of data is returned per request Cursor mode

### ISSUE THREAD

**Issue by persnalaunt** [tweepy/tweepy#1182]
A few days ago, I modified the crawler code according to the tutorial. (http://docs.tweepy.org/en/latest/cursor_tutorial.html)

oldcode：
```
while len(new_tweets) > 0:
   new_tweets = api.user_timeline(screen_name = screen_name, count = 200, max_id = maxid)
   alltweets.extend(new_tweets)
   maxid = alltweets[-1].id - 1
```

newcode：
```
for status in tweepy.Cursor(api.user_timeline(screen_name = screen_name)).items():
    process_status(status)
```

but In newcode Cursor mode, only one row of data is returned per request. 
So that , before it reached  RateLimitError,  only get about  20000 row of data 
but in old way, i total get about  300000 row of data , before it reached  RateLimitError. 
(maybe it  fetch 200 row of data in per request?)

Is there something wrong with my code or the Original  tweetpy's API was designed be that?
I hope Cursor mode will return as much data as possible  in per request.

**Comment by Harmon758** [comment]
> ```
> for status in tweepy.Cursor(api.user_timeline(screen_name = screen_name)).items():
>     process_status(status)
> ```

This will error with `tweepy.error.TweepError: This method does not perform pagination`.
Instead, `screen_name` should be passed as a parameter to the `Cursor` constructor.
See http://docs.tweepy.org/en/latest/cursor_tutorial.html#passing-parameters-into-the-api-method.

You can still pass the count parameter to the `Cursor` constructor, e.g.:
```py
for status in tweepy.Cursor(api.user_timeline, screen_name = screen_name, count = 200).items():
    process_status(status)
```
The `Cursor` will pass the argument to `user_timeline` for each request, so that it'll retrieve up to 200 Tweets, instead of the default of 20.

**Comment by persnalaunt** [comment]
oh man，you are my saver
