### ISSUE TITLE
Update Read the Docs build

### ISSUE THREAD

**Issue by bjarkemoensted** [tweepy/tweepy#1184]
I think the documentation contains an error in the section regarding asynchronous streaming: [http://docs.tweepy.org/en/latest/streaming_how_to.html#async-streaming](url). The docs state to use async=True, but the correct argument appears to be is_async=True.

**Comment by Harmon758** [comment]
This was fixed with https://github.com/tweepy/tweepy/commit/91691b7e0653b33d0f1d2ac8eaae6167ee96b8fd (#1143, which was a duplicate of #1069).
The documentation simply hasn't been built yet since then:
https://readthedocs.org/projects/tweepy/builds/
I believe @joshthecoder might have to trigger a build manually.

**Comment by Harmon758** [comment]
There is now a [new Read the Docs build](https://readthedocs.org/projects/tweepy/builds/8964149/) with the updated changes now at https://tweepy.readthedocs.io/en/latest/ and http://docs.tweepy.org/en/latest/.
