### ISSUE TITLE
I'm just changing the query, I can access the last one-day data

### ISSUE THREAD

**Issue by yziyay** [tweepy/tweepy#1186]
hello I'm pulling data with the same query last month using "Tweepy". I have been taking data for the last two days only until 2019-03-31 08:35. When I change the query, the data I took until 2019-03-21 is happening. and don't get any error. I have the possibility that the query word has not been twitt about for the last week but I'm getting 150 twit now while I get about 2000 twit each week. can you help me.

**Comment by Harmon758** [comment]
It's unclear what your issue is. From what I can understand, you changed your query and you're getting less Tweets as responses? This shouldn't be unexpected depending on the queries you're using.

> I have been taking data for the last two days only until 2019-03-31 08:35.

This seems to contradict what you say afterwards.

> When I change the query, the data I took until 2019-03-21 is happening. and don't get any error.

What do you mean the data "is happening"? When did you change your query?
Is it possible for you to provide the exact queries you're using, that you changed from and to?

What API methods/endpoints are you using?
This isn't actionable, and it's very difficult to help you without more information and clarification.

**Comment by yziyay** [comment]
my query is "vuslat" every week take about 2000 twits, end of date= last one week
today i write my query again "vuslat" ,187 twits, end of date=2019-03-29 23:11:28

**Comment by Harmon758** [comment]
So the query did not change?
What is the exact API method/endpoint you're using and how are you using it?

**Comment by yziyay** [comment]
I guess no one is tweeting about it. Thank you
