### ISSUE TITLE
Seeking code example: How can I get timeline tweets of an user containing specific keywords?

### ISSUE THREAD

**Issue by burningbob333** [tweepy/tweepy#1187]
`def get_tweets_from_self_timeline(self,num_tweets):`
       `     tweets=[]`
 `for tweet in Cursor(self.twitter_client.user_timeline,id=self.twitter_user,q="cupcake").items(num_tweets):`
            `print(tweet.text)`
            
I want tweets from a specific user containing the keyword "cupcake".The above code runs ,however prints also those tweets not containing the given keyword.How can I solve this?

**Comment by Harmon758** [comment]
`q` is not a valid parameter for [`API.user_timeline`](http://docs.tweepy.org/en/latest/api.html#API.user_timeline) or the [user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline). 
If you simply want to check if the Tweet contains a keyword, you can just manually filter within the loop for that keyword, e.g. `if "cupcake" in tweet.text:`.
Otherwise, you'll have to use the [standard search endpoint](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html) using [`API.search`](http://docs.tweepy.org/en/latest/api.html#API.search) with [standard search operators](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators), e.g. "from:burningbob333 cupcake".

GitHub issues should be used to report issues with the library.
They are not a medium for requesting help with Tweepy or Python.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by burningbob333** [comment]
Ok.
