### ISSUE TITLE
Got some issue while running twitter_streaming.oy

### ISSUE THREAD

**Issue by rewatiraman7250** [tweepy/tweepy#1206]
import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.

I got this issue can anyone help here?

**Comment by Harmon758** [comment]
Can you provide the full traceback along with any relevant code?
As well as the Tweepy version you're using and information about your environment (Python version, etc.).

**Comment by rewatiraman7250** [comment]
I am using Andaconda here with these versions below

Microsoft Windows [Version 10.0.17134.706]

![image](https://user-images.githubusercontent.com/22153611/57118954-3abbaf00-6d84-11e9-98b2-1da761be9d0f.png)

![image](https://user-images.githubusercontent.com/22153611/57118972-5de65e80-6d84-11e9-8f4e-25f163f8fefc.png)

![image](https://user-images.githubusercontent.com/22153611/57119015-af8ee900-6d84-11e9-9c60-589798c59fbf.png)

[path_val.txt](https://github.com/tweepy/tweepy/files/3140595/path_val.txt)

**Comment by Harmon758** [comment]
Thanks for following up.

Based on a quick search of the issue, it seems like this is [a known issue with PyCharm](https://youtrack.jetbrains.com/issue/PY-27234), which you seem to be using. According to the issue, it was fixed in version 2019.1.
Alternatively, you can try the steps here: https://stackoverflow.com/a/54240362/6191255

Regardless, this isn't an issue with Tweepy.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python, Anaconda, or PyCharm.

**Comment by rewatiraman7250** [comment]
Thanks Harmon . I followed the above link and updated Anaconda .
It is working now.
