### ISSUE TITLE
Possibility to close async threads upon disconnect?

### ISSUE THREAD

**Issue by Quebert90** [tweepy/tweepy#1224]
Hello there, 

I am looking for a possibility to close async threads when they are disconnected. 
The issue I face (restarting a stream with new filters every few minutes) is having tons of running but disconnected threads after a while. 

Is there a way to close these threads?

Thanks!

**Comment by ParkerShamblin** [comment]
+1

**Comment by Quebert90** [comment]
Another thing I encountered was that **disconnected threads do not stop pulling data** - even if I ignore the memory leak that happens with all these zombie threads not properly closing.  

If I start a new async thread and disconnect the old one (a simple "stop current filter thread and start a new one with a different filter" scenario), the old one is still pulling data. 

This will end up in rate limiting after a few threads, since my filter does not completely change (I am filtering on current trends in my country where not all of them constantly change). For Twitter however all trends per thread (in this case could have duplicate trends in multiple threads) count against my rate limit.  Depending on the trend size, I could even run into rate limiting with 2 threads, whereas 1 thread would not limit at all.

**Comment by ifeve** [comment]
I don't know whether this is correct, I looked up a similar question that may be helpful.
https://stackoverflow.com/questions/14103133/how-to-properly-close-a-tweepy-stream

**Comment by Harmon758** [comment]
I'm unable to reproduce this with Tweepy v3.10:
```py
>>> threading.enumerate()
[<_MainThread(MainThread, started 38500)>]
>>> stream.filter(track=["test"], is_async=True)
>>> thread = stream._thread
>>> thread
<Thread(Thread-1, started 33348)>
>>> thread.is_alive()
True
>>> threading.enumerate()
[<_MainThread(MainThread, started 38500)>, <Thread(Thread-1, started 33348)>]
>>> stream.disconnect()
>>> thread.is_alive()
False
>>> threading.enumerate()
[<_MainThread(MainThread, started 38500)>]
```
and there haven't been any relevant changes to streaming in Tweepy v3.10 since before this issue was opened.

Can you provide a reproducible example (MCVE/SSCCE) of the thread remaining alive after the stream has been disconnected?

Even if the thread somehow continued to run, https://github.com/tweepy/tweepy/commit/9a9e2f098942d733537a0c4fc21af0b948d12db3 should now properly close the requests `Session` so that there's no chance of the connection persisting.

As for the issue brought up in the Stack Overflow question, it should now be resolved with https://github.com/tweepy/tweepy/commit/37e701e2193dcf617e7235d3b004f790c5ff784e, by allowing the stream to disconnect when keep-alive signals are received.  See also #773 and #897.
