### ISSUE TITLE
Results in Json format

### ISSUE THREAD

**Issue by 121eddie** [tweepy/tweepy#1225]
A typical search_user(id) request returns a list containing the _json string.
Is it possible to requeest json results only

**Comment by Harmon758** [comment]
I assume you're referring to [`API.search_users`](https://tweepy.readthedocs.io/en/latest/api.html#API.search_users) since `search_user` doesn't exist anywhere in this library.
`API.search_users` returns a list of User objects. Not a list containing a JSON string.
The [User object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object) is simply a model representation of the raw JSON received for each user.
To get the raw JSON that was used to construct each User object, you can simply use the `_json` attribute:
https://github.com/tweepy/tweepy/blob/cf172c6923cb019734a10f54f8a2d530658326a8/tweepy/models.py#L144-L149
