### ISSUE TITLE
Search queries not matching up with rate limit

### ISSUE THREAD

**Issue by tinkermachine** [tweepy/tweepy#1231]
My search query of ONE keyword seems to use up 7 points from my limit. Is this expected?

Rate Limit before query: 450
```
query = 'BigLittleLies'
tweets = tw.Cursor(api.search,
                  q=query,
                  tweet_mode = 'extended',
                  result_type = 'mixed',
                  lang="en",
                  since=date_since).items(max_tweets)
```
Rate Limit after query: 443

Is this expected behavior?

**Comment by Harmon758** [comment]
I'm unable to reproduce this by simply creating the Cursor, as is expected, since doing so does not send any requests to Twitter's API.

If this occurs after you iterate through the Cursor, then this is expected behavior, since the purpose of a Cursor is to provide paginated results from multiple requests to the API.
See https://developer.twitter.com/en/docs/basics/cursoring and https://tweepy.readthedocs.io/en/latest/cursor_tutorial.html.

The standard search API returns up to 100 Tweets per page, with a default of 15 if the `count` parameter isn't specified. This means that if you're iterating over about 90 - 105 Tweets, you're making 7 separate requests to the API for each page of results. The Cursor simply does this automatically when you use it as an iterator.
See https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.

**Comment by tinkermachine** [comment]
> The standard search API returns up to 100 Tweets per page, with a default of 15 if the count parameter isn't specified. This means that if you're iterating over about 90 - 105 Tweets, you're making 7 separate requests to the API for each page of results. The Cursor simply does this automatically when you use it as an iterator.

This is interesting. So I am in fact specifying a max_tweets = 100 in my query. I assume in this case Cursor does not have to iterate as the API allows me 100 tweets per request. 

This is my full code:
`    query = 'biglittlelies'
    max_tweets = 100
    date_since = "2019-06-01"
    print("Starting query")
    tweets = tw.Cursor(api.search,
                       q=query,
                       tweet_mode='extended',
                       result_type='mixed',
                       lang="en",
                       since=date_since).items(max_tweets)
    print("Query succesfully executed")
    print(limit.resources.search)`

**Comment by Harmon758** [comment]
> This is interesting. So I am in fact specifying a max_tweets = 100 in my query. I assume in this case Cursor does not have to iterate as the API allows me 100 tweets per request.

You're using `max_tweets` to specify how many Tweets/items to get from the Cursor. This isn't passed to Twitter's API in any way. You need to specify `count` as a parameter if you want the API to return more than the default 15 results per page.
Again, see https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
