### ISSUE TITLE
Cursors - how do we not start at the beginning?

### ISSUE THREAD

**Issue by NetwarSystem** [tweepy/tweepy#1244]
I have been examining the cursor.py code today, but I'm self taught in Python and not at all hip to object oriented methods. What I'd like to be able to do is specify an integer number of pages beyond the first for the pagination to begin.

The big picture here is that I'm working on profiling U.S. Senators, and a couple of them ***always*** break part way through gathering their followers. It's happened often enough with the same few, I get the idea I'm hitting a pack of old bots that somehow makes the Twitter API angry when they are referenced. Rather than waiting thirteen hours for the API to walk through four million followers to get back to where it broke, it would be great to be able to tell the system to start on page 800 and work back from there.

**Comment by okomarov** [comment]
So, you want to pull down a list of followers that is more than 75,000 items. That's the current Twitter rate limit over a 15-minute period. If you want more you need to wait in any case the next window but you can:
* use the `wait_on_rate_limit=True` when instantiating the API (http://docs.tweepy.org/en/latest/api.html), and the cursoring will automatically wait for the next window. This will block the execution. 
* abort execution on rate limit error, note down the current cursor id, and restart in 15 minute from the cursor id. For this, you need to write your own cursoring: https://developer.twitter.com/en/docs/basics/cursoring.html

**Comment by Harmon758** [comment]
First of all, you should fix or handle the error you're encountering when iterating through the Cursor.
Without further information like a traceback and your code, it's difficult to determine what the issue is, whether you're encountering a rate limit or otherwise.

As for your question, this is dependent on what type of iterator is being used by the Cursor.
It seems like you're using the [followers/list](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-list) or [followers/ids](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-ids) endpoint with [`API.followers`](https://tweepy.readthedocs.io/en/latest/api.html#API.followers) or [`API.followers_ids`](https://tweepy.readthedocs.io/en/latest/api.html#API.followers_ids), respectively. If that's the case, since both methods/endpoints accept a `cursor` parameter, the Cursor is using a CursorIterator. This is the iterator that is returned when you use the `Cursor.pages` method.
The CursorIterator has `next_cursor` and `prev_cursor` attributes that you can store and pass as the `cursor` parameter to those methods/endpoints:
https://github.com/tweepy/tweepy/blob/940a42a11ad738c05cd5ab21804ebc255df8f4f6/tweepy/cursor.py#L59-L66

Otherwise, the IdIterator and PageIterator have similar `max_id` and `current_page` attributes, respectively.
