### ISSUE TITLE
how can i get location(lang,lati) for all tweets

### ISSUE THREAD

**Issue by afzal646** [tweepy/tweepy#1252]
**how can i get location(lang,lati) for all tweets**
**I want location of all tweets weather they on the location or not?**
OR can anybody tell on what basic **twitter advance search** filter the locations

there is something if u not on your location but twitter always track u how can i get that hidden parameter?

**Comment by Harmon758** [comment]
The Status object has a `coordinates` attribute.
From [Twitter's documentation of the Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object):
> *Nullable.* Represents the geographic location of this Tweet as reported by the user or client application. The inner coordinates array is formatted as [geoJSON](http://www.geojson.org/) (longitude first, then latitude). Example:
> 
> ```
> "coordinates":
> {
>     "coordinates":
>     [
>         -75.14310264,
>         40.05701649
>     ],
>     "type":"Point"
> }
> ```

> **I want location of all tweets weather they on the location or not?**
> there is something if u not on your location but twitter always track u how can i get that hidden parameter?

I'm not sure exactly what you mean by this, but this attribute is nullable (can be `None`) because if the user or client application doesn't provide a geographic location with the Tweet, then there are no coordinates to retrieve. There is no location information associated with the Tweet if it is not provided with the Tweet when it is created, and there are no "hidden parameter"s.

> what basic **twitter advance search** filter the locations

If you're referring to the [standard search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets), you can use the `geocode` parameter:
> Returns tweets by users located within a given radius of the given latitude/longitude. The location is preferentially taking from the Geotagging API, but will fall back to their Twitter profile. The parameter value is specified by " `latitude,longitude,radius` ", where radius units must be specified as either " `mi` " (miles) or " `km` " (kilometers). Note that you cannot use the near operator via the API to geocode arbitrary locations; however you can use this `geocode` parameter to search near geocodes directly. A maximum of 1,000 distinct "sub-regions" will be considered when using the radius modifier.
