### ISSUE TITLE
Clarification on the stream.filter is_async param

### ISSUE THREAD

**Issue by s2t2** [tweepy/tweepy#1301]
Was reading the [docs](http://docs.tweepy.org/en/latest/streaming_how_to.html#async-streaming) and looking at the [source code](https://github.com/tweepy/tweepy/blob/b3bc1f4236027fbb4ded83dc32fd8065612e2226/tweepy/streaming.py#L382-L389) but still not sure what the implications of the `is_async` param are.

Would anyone be able to explain the impacts of setting this as True vs False?

It would be helpful to update the documentation to provide further clarification.

**Comment by Harmon758** [comment]
As the documentation you linked says:
> Streams do not terminate unless the connection is closed, blocking the thread. Tweepy offers a convenient **is_async** parameter on **filter** so the stream will run on a new thread.

This is also seen in the source code you linked, where a separate thread is used for the stream.
Async and threading are general Python/programming concepts that are not unique to Tweepy.

The only misunderstanding that might arise is from the name of the parameter, based on which one might assume that setting it will cause the method to be awaitable, but the documentation clearly says that a new thread is used instead. The reason for the misleading parameter name is that this functionality was added a decade ago, before the existence of asyncio, and the name of the parameter has only changed once since then (for the unrelated reason of avoiding using the async reserved keyword with Python 3.7). However, this inconsistency will likely be resolved soon anyway, once [proper asynchronous support is added](https://github.com/tweepy/tweepy/issues/732).

**Comment by s2t2** [comment]
Thanks @Harmon758 for your quick responses to this and other issues and comments I have posted.  I understand your desire to close as many issues as possible, and I understand your job is a difficult one.

Please realize my goal, and the goal of other issue creators and commenters is to either solve an issue with the package or gain a better understanding of the package's functionality.

It's clear you have extensive Python knowledge, however I encourage you to consider the fact that others might not share all aspects of your knowledge.

The goal of documentation should be to provide a clear understanding to the user of the package. In this case, after reading the documentation and also your comment above, as a reader I am still left wondering what the practical implications are for the asynchronous parameters. 

I encourage you to strive to prioritize providing a great customer experience as you continue in your package maintenance efforts.

Thank you for your time and efforts.

**Comment by Harmon758** [comment]
GitHub issues for this library are primarily intended for issues with the library itself.
For support, there's [the Discord server for Tweepy](https://discord.gg/bJvqnhg), which is also linked in the README, and where I routinely answer all relevant questions and requests for help.
This, along with other forums, such as Stack Overflow, would be more appropriate places to ask for help with using the library or for questions about the library.

As for the documentation, its purpose is to document Tweepy, not to cover aspects of Python or general programming concepts. For that, Python has its own documentation. Specifically, in this case, there is [the documentation for asyncio](https://docs.python.org/3/library/asyncio.html) and [threading](https://docs.python.org/3/library/threading.html).

The parameter itself is not asynchronous, as that doesn't really make much sense. Rather, it's a normal parameter which will run the stream asynchronously as a separate thread when set to `True`. The main purpose of this is for the main thread to continue to run without being blocked by the `Stream.filter` call, while the stream itself runs in parallel. However, these days, "async" or running things asynchronously, generally refers to the asyncio standard library, which has been part of the standard library since Python 3.4 and allows for coroutines within a single thread. For more information, I'd encourage you to research the topic on your own, e.g. by searching for "asynchronous programming", "coroutines", "Python threading", etc. If you have further questions, feel free to ask in the Discord server.
