### ISSUE TITLE
Can't make tweepy comunicate with discord.py

### ISSUE THREAD

**Issue by frazanolo** [tweepy/tweepy#1350]
Hey, I'm trying to do a twitter monitor (it takes tweets from the wanted users using Streaming and sends them istantly to discord using webhooks) but i don't know why it doesn't stream the tweets. I also used python requests to get users IDs from their name (get request to the website http://gettwitterid.com). Now, I used discord.py to make a discord bot with the command !add and !remove, that should get the argument account (e.g. !add Cristiano) and pass it as a parameter in the request to the website i said above to get its ID. Once i get the ID (everything works fine until here) i append it to the accounts list, that i will pass as a filter to my stream class myStream.filter(follow=accounts). The problem is that it runs the bot but it doesn't run the twitter monitor.... how can i do? Will put my code here: https://sourceb.in/970e8af318

**Comment by MichaelCurrin** [comment]
Take the streaming filter and run it alone. With a hand coded list of handles.

Perhaps you need @ to be added or removed from handle.

Also BTW you can use Tweepy to lookup a user by ID and get their handle on the returned User object. You might even be able to do batch lookup like the batch tweet IDs lookup

**Comment by MichaelCurrin** [comment]
Maybe there is just low activity? Try follow your own account and make a tweet.


From tweepy docs:

> This example shows how to use filter to stream tweets by a specific user. The follow parameter is an array of IDs.
> myStream.filter(follow=["2211149702"])

See if that works for our own account and your own stream instance.

See also this issue #981 - the description says there is a limitation.

> `stream.filter(follow=['12345'])` includes tweets at someone and RT

If you don't come right, use `.search` API to get the last 20 or so tweets from named users, though of course you'd have to run that periodically to pull in live tweets.

**Comment by frazanolo** [comment]
i've been doing this with my account since i started and the problem is not that because when i run the single tweepy file it works perfectly, but if i ask it to follow the accounts that i got from the other file it doesn't work anymore

**Comment by Harmon758** [comment]
Since discord.py bots run asynchronously, you'll need to [use the `is_async` parameter to run the stream in a separate thread](https://tweepy.readthedocs.io/en/latest/streaming_how_to.html#async-streaming).
Otherwise, the stream will [block](https://discordpy.readthedocs.io/en/latest/faq.html#what-does-blocking-mean) the Discord bot from running.

Note, Requests is also blocking and is liable to cause issues with your Discord bot.

You can also use Twitter's API with [the GET users/show endpoint](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-show) using [`API.get_user`](https://tweepy.readthedocs.io/en/latest/api.html#API.get_user) or [the GET users/lookup endpoint](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup) using [`API.lookup_users`](https://tweepy.readthedocs.io/en/latest/api.html#API.lookup_users) to retrieve [User objects](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object) by ID with attributes including `name`, `screen_name`, etc. Note though, that Tweepy also uses Requests internally. For asyncio support for Tweepy, see #732.
