### ISSUE TITLE
str to tweepy status object conversion

### ISSUE THREAD

**Issue by sudoplox** [tweepy/tweepy#1352]
I saved tweepy status object in a csv, now when I'm trying to read it, it is showing its type as str, is there any way to change its type to tweepy.Status object?

**Comment by MichaelCurrin** [comment]
Use `csv.DictReader` and then see if you can create a local `tweepy.Status(...)` by passing in values.

Alternatively keep working with the row as dict or create a class which has some of Status fields that you care about, though you'll lack methods.

Also JSON file might be a better choice for storage due to the nested fields.

**Comment by MichaelCurrin** [comment]
Another thought. Just write out the tweet ID to your CSV.

Then when you need to use it, do an API lookup in tweepy to fetch that tweet. Now you'll have the latest engagements stats on it and you can do actions like retweet it.
You can even use the bulk ID lookup if you have 100 tweets to fetch at once.

**Comment by MichaelCurrin** [comment]
Also try lookup `pickle` in Python. You'll write in a format different to CSV but it means you can write some Python objects and read them back in again as full objects with no parsing needed.

**Comment by Harmon758** [comment]
You'd need to convert the data into JSON to be able to use [the `Status.parse` class method](https://github.com/tweepy/tweepy/blob/c29237291e5c4ed60331ef63fce51a74bef297c9/tweepy/models.py#L83-L115).
I'd recommend storing the data as JSON to begin with if you need to reconstruct the Status object.
