### ISSUE TITLE
It does not look like Cursor returns json or anything that can be easily parsed.  Am I missing something?

### ISSUE THREAD

**Issue by SteveStrong** [tweepy/tweepy#1353]
# http://blog.chapagain.com.np/python-get-twitter-tweets-using-tweepy-library/
    def get_fortnite_tweets(self, num_tweets):
        fortnite_tweets = []
        for tweet in Cursor(api.search, q='fortnite').pages(num_tweets):
            fortnite_tweets.append(tweet)
        return fortnite_tweets

this code returns the string or search_request below,  I just want to json,   any thoughs on parsing this?

Status(_api=<tweepy.api.API object at 0x0000018F368A36C8>, _json={'created_at': 'Sat Apr

**Comment by MichaelCurrin** [comment]
The Status object output you see is just a summary of the many fields inside the tweet object.

Use what the linked tutorial says. e.g. ```item.text```

You probably don't need to deal with the ```item._json``` attribute and parse any JSON.

**Comment by MichaelCurrin** [comment]
I've listed most of the attributes here:

https://michaelcurrin.github.io/python-twitter-guide/#/models

Also note that `Cursor(q=q, count=100).items(tweet_count)` will be more useful for you. It will return tweets rather than pages of tweets, so you don't need the append step. And it improves on the default count of 20.

If you use `.items(500)` you'll get up to 500 tweets. If you use `.pages(500)` you'll get 100x500 = 50,000 tweets!

For more info see guide https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=get-more-tweets

**Comment by Harmon758** [comment]
That's simply the string representation of the Status object, which corresponds to the [Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) that Twitter's API returns.
You can access the raw JSON by using the `_json` attribute of the Status object.
