### ISSUE TITLE
How to BreakDown The Resultset?

### ISSUE THREAD

**Issue by ekkirizki** [tweepy/tweepy#1387]
I was confused to breakdown the resultset, i have been using cursor but it still error.
this my first code, it said 

> TweepError: [{'code': 214, 'message': 'invalid cursor'}]

`query1 = tweepy.Cursor(api.list_direct_messages).items()`
`dms = [status for status in query1]`
`dms`

and this is my second tried, it was saying
> This method does not perform pagination

`query1 = tweepy.Cursor(api.list_direct_messages()).items()`
`dms = [status for status in query1]`
`dms`

please help me, i'd confused....

**Comment by Harmon758** [comment]
The first set of code is the correct way to go about this.
However, there was a bug with using a cursor with `API.list_direct_messages`. See #1261.
This should be fixed with #1262 in the master branch.
In the future, please make sure you're using the latest development version when reporting issues.
Otherwise, you'll have to wait until Tweepy v3.9 is released with the fix.

For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
