### ISSUE TITLE
Question of list_direct_messages

### ISSUE THREAD

**Issue by ly1n** [tweepy/tweepy#1398]
The document says that `Returns all Direct Message events (both sent and received) within the last 30 days. Sorted in reverse-chronological order.`.
But I can not get the all DM within the last 30 days. 

When I use `api.list_direct_messages()` could get less messages. And use `api.list_direct_messages(count=50)` could get a little more messages but it did not reach 50. What's problem? More than 50 DMs in the last 30 days.

And I can not use the `cursor` parameter, it will cause error `tweepy.error.TweepError: [{'code': 214, 'message': 'invalid cursor'}]
`. I use it like `api.list_direct_messages(count=2, cursor=-1)` or `api.list_direct_messages(count=2, cursor=1)`

**Comment by Harmon758** [comment]
The `count` parameter defaults to 20, and only specifies the max number to be returned.
Twitter's API can very well return less than that number.
See [the documentation for the GET direct_messages/events/list endpoint](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/list-events).

As for the error with using a cursor with `API.list_direct_messages`, see #1261.
This should be fixed with #1262 in the master branch.
In the future, please make sure you're using the latest development version when reporting issues.
Otherwise, you'll have to wait until Tweepy v3.9 is released for the fix.
