### ISSUE TITLE
Spyder Issues with Twitter

### ISSUE THREAD

**Issue by Conorm45** [tweepy/tweepy#1400]
I keep getting this response when running code : AttributeError: module 'tweepy' has no attribute 'auth'
I know that the code is right. Just wondering if anyone knew had to overcome this :)
Thanks for any help.

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Do you have another file or folder/module named Tweepy in your path?
What version of Tweepy are you using?
Can you provide a reproducible example (MCVE/SSCCE)?

**Comment by Conorm45** [comment]
Thanks for your timely response. Yes I could have another path named tweepy
in my path. What would be the easiest way to check if this is the case. Not
too sure what version it is just installed tweepy through Pip

**Comment by Conorm45** [comment]
This is the code I have been getting.
  File "/Users/conormurphy/Desktop/MSc Fintech/twitter_search.py", line
193, in <module>
    main()

  File "/Users/conormurphy/Desktop/MSc Fintech/twitter_search.py", line
189, in main
    api = tw_oauth(authfile)

  File "/Users/conormurphy/Desktop/MSc Fintech/twitter_search.py", line 85,
in tw_oauth
    auth1 = tweepy.auth.OAuthHandler(ak[0].replace("\n",""),
ak[1].replace("\n",""))

AttributeError: module 'tweepy' has no attribute 'auth'

**Comment by Conorm45** [comment]
sorry i am using version 3.8.0

**Comment by Harmon758** [comment]
You're likely importing another file/module in your path rather than the Tweepy library.
You can try to use the module's [`__file__`](https://docs.python.org/3/reference/import.html#__file__) attribute to determine the location of the file/module you're importing, e.g.:
```
>>> import tweepy
>>> tweepy.__file__
'C:\\Program Files\\Python38\\lib\\site-packages\\tweepy\\__init__.py'
```
You can also use [`inspect.getfile`](https://docs.python.org/3/library/inspect.html#inspect.getfile), e.g.:
```
>>> import tweepy
>>> import inspect
>>> inspect.getfile(tweepy)
'C:\\Program Files\\Python38\\lib\\site-packages\\tweepy\\__init__.py'
```

For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
