### ISSUE TITLE
How can i get direct message with on_direct_message

### ISSUE THREAD

**Issue by MrMahdi313** [tweepy/tweepy#1418]
![carbon](https://user-images.githubusercontent.com/20910185/90676620-8e038a80-e271-11ea-961f-bba83424c267.png)
I run this code 
but program finished with exit code 0
i dont get any error & program finish after 2-3 seconds.

**Comment by Harmon758** [comment]
User streams have been deprecated and retired since August 23rd, 2018 in favor of the new Account Activity API.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
