### ISSUE TITLE
when calling lists_membership on a member of class user, the wrong user is queried

### ISSUE THREAD

**Issue by brett-schneider** [tweepy/tweepy#1443]
after querying people i follow (frens = api.friends), i wanted to find out in which list i or others keep them (frens[0].lists_membership()). from my understanding, frens[0].lists_membership() should return a list of lists that fren[0] is a member of. however i'm getting a list of lists that auth_user is a member of. i looked in model.py, which looks fine. could there be an issue with the unwrapping of resultset?

**Comment by brett-schneider** [comment]
this looks suspicious:
user=self.screen_name
at [models.py line 199](https://github.com/tweepy/tweepy/blob/master/tweepy/models.py#L199)

**Comment by Harmon758** [comment]
To clarify, this occurs because `User.lists_membership` passes the `screen_name` as `user` to `API.lists_membership`:
https://github.com/tweepy/tweepy/blob/9146c2e1beace83888b459bb622ab53c4019dd39/tweepy/models.py#L199  which is not an allowed parameter, so the GET lists/memberships endpoint defaults to the memberships for the authenticating user instead.
