### ISSUE TITLE
3-legged Oauth for my Twitter Python script

### ISSUE THREAD

**Issue by KieranDL** [tweepy/tweepy#1464]
I have the below basic python script and I would like to use the 3-legged Oauth that the Twitter API makes available to allow anyone to sign in with their Twitter account and use the script.

At the moment they can simply enter their Keys/Tokens to use it but I would like a standard Twitter user to be able to use it and not just a developer who knows these.

```
import tweepy

print('Please enter your Consumer Key')
consumer_key = input()
print('Please enter your Consumer Secret')
consumer_secret = input()
print('Please enter your Access Token')
key = input()
print('Please enter your Access Secret')
secret = input()

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(key, secret)
api = tweepy.API(auth, wait_on_rate_limit=True)

screen_name = auth

for follower in api.followers(screen_name): 
    print(follower.screen_name) 
```
Do I have to use my script in a web app to make this possible or is there something I can add to the script for this authorisation?

I would like it to work similarly to a third party app that you would grant access to get/post from your twitter.``

**Comment by stratospher** [comment]
What did you enter as the callback URL in twitter app settings?

**Comment by Harmon758** [comment]
I've rewritten the authentication documentation with https://github.com/tweepy/tweepy/commit/f9a722bae8cce368b9f8fd447c418e1034c32178, which should hopefully answer this question.

You should look into using [PIN-based OAuth](https://tweepy.readthedocs.io/en/latest/authentication.html#pin-based-oauth). Otherwise, you'll have to use a callback URL.
