### ISSUE TITLE
search_users by location returns duplicate users

### ISSUE THREAD

**Issue by yzhaoinuw** [tweepy/tweepy#1465]
Hello Tweepy developers, I wanted to get a list of users who are located in Rochester, NY (based on their profile), with the following snippet:
```
users = []
place = 'Rochester, NY'
for user in tweepy.Cursor(api.search_users,q='location:'+place).items(50):
    users.append(user.screen_name)
```

I expected it to return a list of unique users located in Rochester, NY, but then I got  a list of the same user, shown below.

`
['ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits', 'ajcustomsuits']
`

What did I do wrong?

**Comment by Harmon758** [comment]
I don't think the [GET users/search endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-search) that `API.search_users` uses has [an explicit location search option](https://twittercommunity.com/t/get-people-by-location/11612/2).

However, this does seem to be a bug, although with Twitter's API, rather than with Tweepy.
Even with calls to the specific pages from 1-51, e.g. `api.search_users(q="location:Rochester, NY", page = 51)`, each page returns that user as the single result. Oddly enough, it stops at page 51 and there is no page 52.
It might be worth making a forum post at https://twittercommunity.com/c/twitter-api/64 about this.

**Comment by Harmon758** [comment]
It seems like [this is a longstanding issue that won't be fixed before a Twitter API v2 equivalent endpoint is released](https://twittercommunity.com/t/odd-pagination-behavior-with-get-users-search/148502).
#958 and #959 are also related.
