### ISSUE TITLE
api.update_profile_background_image returns "Sorry, that page does not exist"

### ISSUE THREAD

**Issue by TallGorilla** [tweepy/tweepy#1466]
Im creating a script that will change the user banner, the point is that **every time it try to change the image** by using `api.update_profile_background_image("the/image/location.png")` it returns `Exception has occurred: TweepError
[{'message': 'Sorry, that page does not exist', 'code': 34}]`

_**_How can i fix this?_**_

Thanks in advance.

**Comment by TallGorilla** [comment]
Closed as i recenlty discovered there is the update_profile_banner option XD

**Comment by Harmon758** [comment]
The [POST account/update_profile_background_image endpoint](https://web.archive.org/web/20190809210233/https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/post-account-update_profile_background_image) that `API.update_profile_background_image` used has been deprecated and removed, since background profile images have not been available or visible on Twitter.com since July 2015.
https://twittercommunity.com/t/upcoming-changes-to-the-developer-platform/104603

I've gone ahead and removed the method with https://github.com/tweepy/tweepy/commit/8dba191518366fb756440302eff86d5a868e0306.
