### ISSUE TITLE
Search method is not working with list query

### ISSUE THREAD

**Issue by root-T2** [tweepy/tweepy#1540]
Tweepy 3.10.0
Since yesterday, query search with `list:user/slug` is not working.

```
query = "list:easoncxz/nz-official"
x = list(tweepy.Cursor(api.search, q=query).items(20))
print(len(x))
# → 0
```
This query is working in the web version.
https://twitter.com/search?q=list%3Aeasoncxz%2Fnz-official&src=typed_query&f=live

Normal search appears to be working correctly.
```
query = "twitter"
x = list(tweepy.Cursor(api.search, q=query).items(20))
print(len(x))
# → 20
```
https://twitter.com/search?q=twitter&src=typed_query&f=live

**Comment by root-T2** [comment]
`list:list_id` is not working as well.
```
query = "list:1248785315763859456"
x = list(tweepy.Cursor(api.search, q=query).items(20))
print(len(x))
# → 0
```
web version.
https://twitter.com/search?q=list%3A1248785315763859456&src=typed_query&f=live

**Comment by Harmon758** [comment]
Did this use to work?
This seems like an issue with Twitter's API rather than Tweepy, as it *is* listed as a [standard search operator](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/guides/standard-operators).
Possibly already reported already as well: https://twittercommunity.com/t/standard-search-operator-list-username-slug-returning-empty-statuses/150302

**Comment by Harmon758** [comment]
See also https://twittercommunity.com/t/list-search-does-not-work-with-twitter-api-v1-1/151076.
