### ISSUE TITLE
Inconsistent/different results for cursor example from documentation each time I run it

### ISSUE THREAD

**Issue by koljaoh** [tweepy/tweepy#1560]
I am trying to get all (~3200) tweets from a user (in batches of 200) and would like to utilize the cursor functionality (I can do it without utilizing max_id) but each time I run the script I get a different result (different amount of result, number is random but almost never 200).

```
tweetlist=[]
for status in tweepy.Cursor(api.user_timeline, screen_name='CryptoCobain', tweet_mode="extended", include_rts = False).items(200):

tweetlist.append(status.full_text)
```
I tried various variations of this code for example adding the limit_handler from the documentation as well as adding multiple ways to catch errors:

```
def limit_handled(cursor):
while True:
    try:
        yield cursor.next()
    except tweepy.RateLimitError:
        print("rate limit reached")
        time.sleep(15 * 60)
    except Exception as e:
        print(str(e.__class__.__name__))        
        break 

for status in limit_handled(tweepy.Cursor(api.user_timeline, screen_name='CryptoCobain', tweet_mode="extended", include_rts = False).items(200)):
tweetlist.append(status.full_text)
```

The reason seems to be a StopIteration error:

```
Traceback (most recent call last):
  File "d:\1 projects\investing project\crypto\investment research\Investment Bot\code\twitter\twittermentions.py", line 20, in limit_handled
    yield cursor.next()
  File "C:\Users\Kol_Y\.conda\envs\crypto\lib\site-packages\tweepy\cursor.py", line 243, in next
    self.current_page = self.page_iterator.next()
  File "C:\Users\Kol_Y\.conda\envs\crypto\lib\site-packages\tweepy\cursor.py", line 158, in next
    raise StopIteration
StopIteration
47
```

Does anybody have an idea why I always get different results and what to do about it? I tried with Python 3.9 and also with Python 3.6, each time setting up a new conda env with nothing but tweepy

There is also a similar stackoverflow question but without answers: https://stackoverflow.com/questions/61683779/tweepy-doesnt-work-when-looking-at-realdonaldtrump-account-inconsistent 

Any input is much appreciated

**Comment by Harmon758** [comment]
`StopIteration` isn't really an error. It simply means the `Cursor` has finished iterating.

The underlying cause of this is that the `IdIterator` that `Cursor` uses for `API.user_timeline` stops iterating on a response/page with 0 results. This is to prevent the `Cursor`/iterator from continuing to make requests indefinitely when there are no more results (e.g. when attempting to retrieve more Tweets than the user has Tweeted). For pagination via `since_id` and `max_id`, Twitter's API provides no other indication that there's no results left like other pagination methods do (such as `next_cursor` being 0), so there's not really a way around this.

For your specific case, you can mitigate the issue by setting `count` to the max of 200, rather than using the default 20.
This should reduce the number of and potentially eliminate responses/pages with 0 results, and has the additional benefit of making fewer requests for the same results.

Alternatively, you can remove your usage of `include_rts` and filter out Retweets yourself.
As [the documentation for the GET statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline) says about `include_rts`:
> When set to *false* , the timeline will strip any native retweets (though they will still count toward both the maximal length of the timeline and the slice selected by the count parameter)

and `count`:
> Specifies the number of Tweets to try and retrieve, up to a maximum of 200 per distinct request. The value of count is best thought of as a limit to the number of Tweets to return because suspended or deleted content is removed after the count has been applied. We include retweets in the count, even if *include_rts* is not supplied. It is recommended you always send *include_rts=1* when using this API method.

You're likely encountering pages with 0 results more than usual with `include_rts` set to `False`, since any Retweets are removed from the results after they've been counted as part of the `count` limit for the page.

As for the Stack Overflow question, that specific account was probably subject to additional issues with eventual consistency: https://github.com/tweepy/tweepy/issues/1361
