### ISSUE TITLE
More frequent / beta releases?

### ISSUE THREAD

**Issue by curtiscook** [tweepy/tweepy#1585]
Hi, 

It's very clear that a ton of amazing work has gone into Tweepy and I thank you for that. 

With the amount of development that goes into the project, I think it would be extremely helpful if versions were cut more than biannually? The latest version is 3.10, which lacks some quality of life upgrades that appear to be slated for 4.0.0. From the looks of it, there are over 800 commits since the last version https://github.com/tweepy/tweepy/compare/v3.10.0...master

Additionally, the documentation appears to be pointing to the latest development version (1230013d per the footer), whereas the title is suggesting that the features work in 3.10.0.  
For example:
https://docs.tweepy.org/en/latest/exceptions.html?highlight=unauthorized#tweepy.errors.Unauthorized

I understand that you can just pip install the latest development from github, but if you're running docker, this forces you to install git in your image and doesn't allow you to specify acceptable semver ranges via pip. (Your only 2 options are to install latest or pin to a commit). This feels less than ideal

**Comment by Harmon758** [comment]
https://github.com/tweepy/tweepy/commit/348232fde0e947008567eef16000010f6243af43 should resolve the immediate issue with the documentation HTML title.

The major remaining feature to be implemented for v4.0 is asyncio support, which I intend to finish before releasing it.
Hopefully, I'll be able to get it done in the next few weeks.
Most of the rest of the remaining [4.0 milestone](https://github.com/tweepy/tweepy/milestone/11) that is yet to be done will likely be pushed to v4.1.

I expect the development time of v4.0 to be a one-off and not the norm, in terms of future versions, as there's multiple major features that have been implemented for it, as well as numerous breaking changes, refactors, etc. I anticipate any bugfix releases (e.g. v4.0.1, etc.) and the next minor release, v4.1, to be released much more promptly, since there shouldn't be anything to block those types of releases, and anything missing could be fairly easily included in the next bugfix or minor release. Whereas for v4.0, I want to make sure everything necessary (e.g. every pertinent breaking change) is included before release, so that a v5.0 won't be required any time soon.
