### ISSUE TITLE
422 Response when using api.search_full_archive

### ISSUE THREAD

**Issue by georgicacristianciobanoiu** [tweepy/tweepy#1608]
When i try the following code:
**for tweet in tweepy.Cursor(api.search_full_archive, label="dev", query="Trump -is:retweet lang:es", maxResults=1,fromDate=1232211.0, toDate=2131423423.0).items(100):, I get the following error message:**
Traceback (most recent call last):
  File "C:\Users\jcciobanoiu\PyCharmProjects\TFG\main.py", line 89, in <module>
    for tweet in tweepy.Cursor(api.search_full_archive, label="dev",
  File "C:\Python39\lib\site-packages\tweepy\cursor.py", line 86, in __next__
    return self.next()
  File "C:\Python39\lib\site-packages\tweepy\cursor.py", line 286, in next
    self.current_page = next(self.page_iterator)
  File "C:\Python39\lib\site-packages\tweepy\cursor.py", line 86, in __next__
    return self.next()
  File "C:\Python39\lib\site-packages\tweepy\cursor.py", line 260, in next
    data = self.method(next=self.next_token, return_cursors=True, *self.args, **self.kwargs)
  File "C:\Python39\lib\site-packages\tweepy\api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "C:\Python39\lib\site-packages\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "C:\Python39\lib\site-packages\tweepy\api.py", line 447, in search_full_archive
    return self.request(
  File "C:\Python39\lib\site-packages\tweepy\api.py", line 267, in request
    raise HTTPException(resp)
tweepy.errors.HTTPException: 422 Unprocessable Entity

**Comment by Harmon758** [comment]
A 422 Unprocessable Entity error
>  is returned due to invalid parameters in the query -- e.g. invalid PowerTrack rules.

In this case, the error message is:
> There were errors processing your request: Invalid 'fromDate':'1232211'. 'fromDate' must be in format 'yyyyMMddHHmm'. For example, '201101012315' for January 1st, 11:15 pm 2011 UTC, Invalid 'toDate':'2131423423'. 'toDate' must be in format 'yyyyMMddHHmm'. For example, '201101012315' for January 1st, 11:15 pm 2011 UTC

Removing the `fromDate` and `toDate` parameters will still error with the message:
> There were errors processing your request: Invalid 'maxResults':'1'. 'maxResults' must be an integer value greater than or equal to 10 and less than or equal to 100

Note, `is:retweet`
> is only available to paid premium subscribers.

so if you're using free sandbox access, removing the `maxResults` parameter will still error with the message:
> There were errors processing your request: Reference to invalid operator 'is:retweet'. Operator is not available in current product or product packaging. Please refer to complete available operator list at http://t.co/operators. (at position 11)

See the documentation for the [premium search APIs](https://developer.twitter.com/en/docs/twitter-api/premium/search-api/api-reference/premium-search) and [premium operators](https://developer.twitter.com/en/docs/twitter-api/premium/search-api/guides/operators).

As for the error messages themselves, https://github.com/tweepy/tweepy/commit/32f00f2a14e65f9caf96c070d0a195abd0c75cf4 should improve `HTTPException` so as to include the messages from `"error"` keys in the response JSON with the exception error message, e.g.:
```pycon
>>> api.search_full_archive(label="dev", query="Trump -is:retweet lang:es", maxResults=1,fromDate=1232211.0, toDate=2131423423.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\GitHub\tweepy\tweepy\api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "D:\GitHub\tweepy\tweepy\api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "D:\GitHub\tweepy\tweepy\api.py", line 447, in search_full_archive
    return self.request(
  File "D:\GitHub\tweepy\tweepy\api.py", line 267, in request
    raise HTTPException(resp)
tweepy.errors.HTTPException: 422 Unprocessable Entity
There were errors processing your request: Invalid 'fromDate':'1232211.0'. 'fromDate' must be in format 'yyyyMMddHHmm'. For example, '201101012315' for January 1st, 11:15 pm 2011 UTC, Invalid 'toDate':'2131423423.0'. 'toDate' must be in format 'yyyyMMddHHmm'. For example, '201101012315' for January 1st, 11:15 pm 2011 UTC
```

Also, I'm not sure why you're attempting to limit `maxResults` to 1 and iterate through 100 results.
If this were successful, you would unnecessarily and inefficiently make 100 separate requests to the API rather than getting all the results in a single request.

For code block usage, see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
