### ISSUE TITLE
User Stream Cursor method not getting correct number of items 

### ISSUE THREAD

**Issue by jalalshabo** [tweepy/tweepy#1609]
The user timeline using cursor items returns a random number of tweets, the issue seems to be persistant with users with more followers such as elon musk, when running it on my friends random twitter account the streaming worked perfectly and got back the correct number of items but not with very popular twitter users. If anyone can explain why that would be fantastic. 

````
for status in tweepy.Cursor(api.user_timeline, screen_name='name of user', tweet_mode="extended").items(500):
        count += 1
        print(status)
        print(count)
````

**Comment by jalalshabo** [comment]
Actually even when streaming a random user, if you ask for a large number of tweets you wont ever get it, usually just depends. I did find a solution though but it requires more requests which if your making a lot of you could easily use up the 1500 per month for user timeline requests.

**Comment by Harmon758** [comment]
For the "elonmusk" account, this is probably an issue with Twitter's API and a variation of #1550.
Otherwise, can you provide a reproducible example (MCVE/SSCCE) of this?

Also, the rate limit for the [GET statuses/user_timeline](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline) endpoint that [`API.user_timeline`](https://tweepy.readthedocs.io/en/v3.10.0/api.html#API.user_timeline) uses is 1500 / 15-min window (for app auth), not per month.
