### ISSUE TITLE
Incorrect response error code for suspended users

### ISSUE THREAD

**Issue by ancientjpeg** [tweepy/tweepy#1616]
In trying to use tweepy to keep track of user suspensions, I've come across an issue. Whenever I use the tweepy.API.lookup_users() method on suspended users, tweepy returns an error with code 17 ('No user matches for specified terms.') as opposed to the more accurate code 63 ('User has been suspended.'). For example, the code snippet:
```python
try:
    usr = api.lookup_users(screen_names=['someSuspendedUser'])
except TweepError as e:
    print(e)
```
generates output:
```
[{'code': 17, 'message': 'No user matches for specified terms.'}]
```
whereas the code
```python
    usr = api.lookup_users(screen_names=['someUser'])
``` 
returns the expected User object for any user who is not suspended.

This may in fact be an issue with the twitter API itself, as the response held by the TweepError returned in the above code displays:
```
<Response [404]>
```
suggesting that the Twitter API may itself just be giving bad info, as code 63 is generally supposed to be associated with a 403 response. That said I'm not positive, hence why I'm raising the issue here, just in case!

**Comment by Harmon758** [comment]
These error codes and messages are from Twitter's API itself, and Tweepy simply passes them along.
This isn't an issue with Tweepy, and I don't think it's really an issue with Twitter's API either.
I suspect error code 17 is used because of the possibility of multiple different users being looked up with that endpoint.
The [documentation for the GET users/lookup endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-users-lookup) says:
> - If a requested user is unknown, suspended, or deleted, then that user will not be returned in the results list.
> - If none of your lookup criteria can be satisfied by returning a user object, a HTTP 404 will be thrown.

and this matches the documented behavior. It makes sense to raise a consistent error code 17 when there's no results to be returned, as the users being looked up might not necessarily all be suspended.

On the other hand, the GET users/show endpoint that `API.get_user` uses does return error code 63 when attempting to retrieve a user that's been suspended.

If you want to though, you could make a post about this on the [Twitter Developers Forums](https://twittercommunity.com/), which would be the appropriate place to discuss this.

**Comment by ancientjpeg** [comment]
Awesome, thanks for all the info!
