### ISSUE TITLE
Documentation: Cursor Code Snippet and RateLimitError

### ISSUE THREAD

**Issue by skilfullycurled** [tweepy/tweepy#1618]
Hello,

I was working with the code snipped entitled [Handling the rate limit using cursors](https://docs.tweepy.org/en/stable/code_snippet.html#handling-the-rate-limit-using-cursors).  

When I run the snippet as originally written using `RateLimitError` it does not handle the error the error as expected, but it does if I replace `RateLimitError` with `TweepError`.  I've put both below with a bit of the Traceback, and have attached the full Traceback as well.

Note: As you can see, I've modified it for using `api.search` and replaced the `time.sleep` with `return` but the same happens with the original.
[rate_limit_error_trackback.txt](https://github.com/tweepy/tweepy/files/6767098/rate_limit_error_trackback.txt)

Aside: Is there documentation for the [Cursor](https://github.com/tweepy/tweepy/blob/master/tweepy/cursor.py) class or is it only within the code itself?

**Original:**

```python
def limit_handled(cursor):
    while True:
        try:
            yield cursor.next()
        except tweepy.RateLimitError:
            print('RateLimitError')
            return

cursor = tweepy.Cursor(api.search, q='#some_tag')

tweets = 0
for tweet in limit_handled(cursor.items()):
    try:
        tweets += 1
    except:
        print(tweets)
```
Traceback:
```python
~/miniconda3/envs/grading/lib/python3.7/site-packages/tweepy/binder.py in execute(self)
    232                     raise RateLimitError(error_msg, resp)
    233                 else:
--> 234                     raise TweepError(error_msg, resp, api_code=api_error_code)
    235 
    236             # Parse the response payload

TweepError: Twitter error response: status code = 429
```
**New:**
```python
def limit_handled(cursor):
    while True:
        try:
            yield cursor.next()
        except tweepy.TweepError as err:
            print(err.response.text)
            return

tweets = 0

for tweet in limit_handled(cursor.items()):
    try:
        tweets += 1
    except:
        print(tweets)

# returns
# {"errors":[{"message":"Rate limit exceeded","code":88}]}
```
[rate_limit_error_trackback.txt](https://github.com/tweepy/tweepy/files/6767105/rate_limit_error_trackback.txt)

**Comment by Harmon758** [comment]
This should be resolved with https://github.com/tweepy/tweepy/commit/cd5f696d09530f86ac0edf1ec0fe0a02578a3920 in [Tweepy v4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0).

Note, that example in the documentation has been replaced now, with https://github.com/tweepy/tweepy/commit/fe5a0508f97326e0be4fddca5db65a655607c2f9 and https://github.com/tweepy/tweepy/commit/5fa6e73bbe677cf2527af7187012f665b825639d.
It never really made much sense to include in the documentation anyway, since `wait_on_rate_limit` handles this.

[Documentation for `Cursor`](https://tweepy.readthedocs.io/en/v4.2.0/pagination.html#tweepy.Cursor) has also been added.
