### ISSUE TITLE
update docs for API.search_tweets

### ISSUE THREAD

**Issue by ablil** [tweepy/tweepy#1668]
The method **search_tweets** is not present in the **API** class, even though it shows up in the [docs](https://docs.tweepy.org/en/stable/api.html#tweepy.API.search_tweets).

I found that It is replaced with the method **seach**.
check the following screenshot:
![image](https://user-images.githubusercontent.com/25986426/134817942-ae654f00-9959-4557-91be-2a70265e351d.png)

**Comment by Harmon758** [comment]
I'm unable to reproduce this with Tweepy v4.0.0:
```pycon
>>> import tweepy
>>> 'search_tweets' in dir(tweepy.API)
True
>>> 'search' in dir(tweepy.API)
False
```
[Tweepy v4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0), which renamed `API.search` to `API.search_tweets`, was released yesterday.
Since this is the latest release, it is now the version that the stable version of the documentation refers to and is documenting.
