### ISSUE TITLE
V2 Get_Tweet cannot return the data for tweet_fields

### ISSUE THREAD

**Issue by ycchanau** [tweepy/tweepy#1670]
<img width="1440" alt="Screenshot 2021-09-27 at 7 55 24 PM" src="https://user-images.githubusercontent.com/43056995/134903568-0df2589b-ec57-4e62-9c19-114458428910.png">

It seems that the get_tweet cannot correctly return the data of the tweet. I can see the data in the response content but it seems that the Response object doesn't contain the data like "lang".

**Comment by Harmon758** [comment]
I'm unable to reproduce this:
```pycon
>>> tweet_fields=["text", "lang", "public_metrics"]
>>> temp = client.get_tweet(id="1442329775314403332", user_auth=False, tweet_fields=tweet_fields)
>>> temp
Response(data=<Tweet id=1442329775314403332 text=起晚了迟到了 https://t.co/bjp7Yd2Khf>, includes={}, errors=[], meta={})
>>> 
>>> temp.data
<Tweet id=1442329775314403332 text=起晚了迟到了 https://t.co/bjp7Yd2Khf>
>>> tweet = temp.data
>>> 
>>> tweet.lang
'zh'
>>> tweet.public_metrics
{'retweet_count': 10, 'reply_count': 9, 'like_count': 173, 'quote_count': 1}
>>> 
>>> tweet["lang"]
'zh'
>>> tweet["public_metrics"]
{'retweet_count': 10, 'reply_count': 9, 'like_count': 173, 'quote_count': 1}
>>> 
>>> tweet.data
{'id': '1442329775314403332', 'text': '起晚了迟到了 https://t.co/bjp7Yd2Khf', 'public_metrics': {'retweet_count': 10, 'reply_count': 9, 'like_count': 173, 'quote_count': 1}, 'lang': 'zh'}
>>> tweet["data"]
{'id': '1442329775314403332', 'text': '起晚了迟到了 https://t.co/bjp7Yd2Khf', 'public_metrics': {'retweet_count': 10, 'reply_count': 9, 'like_count': 173, 'quote_count': 1}, 'lang': 'zh'}
```

[`Response`](https://tweepy.readthedocs.io/en/v4.0.0/client.html#tweepy.Response) is a `namedtuple`. Here, within its `data` field, is a single `Tweet` object.

The string representation of a `Tweet` object will only ever include its ID and text. This was an intentional design choice, to reduce the excess of information that could be displayed when printing all the data as the string representation, as with `models.Status`. The ID and text are the only default / guaranteed fields, so the string representation remains consistent and unique, while still being concise. This design is used throughout the API v2 models.

To access the data of the `Tweet` object, you can use attributes or keys (like a dictionary) to access each field.
If you want all the data as a dictionary, you can use the `data` attribute/key.

**Comment by persep** [comment]
Is this documented anywhere?

**Comment by Harmon758** [comment]
https://tweepy.readthedocs.io/en/v4.12.1/faq.html#why-am-i-not-getting-expansions-or-fields-data-with-api-v2-using-client
