### ISSUE TITLE
get_users_tweets returns a random (normally incomplete) subset of a user's tweets

### ISSUE THREAD

**Issue by pbeart** [tweepy/tweepy#1731]
```
import tweepy

client = tweepy.Client(bearer_token=BEARER_TOKEN)

n = 0
for responses in tweepy.Paginator(client.get_users_tweets,
                              "44196397",
                              end_time="2030-11-06T00:00:01Z",
                              start_time="2010-11-06T00:00:01Z",
                              max_results=100).flatten(limit=250):
    if responses.data is None: continue
    n+=len(responses.data)

print(n)

n2 = 0
for tweet in client.get_users_tweets('44196397',
                                     max_results=100,
                                     tweet_fields=["created_at",
                                                   "referenced_tweets"],
                                     expansions=["referenced_tweets.id"]).data:
    n2+=1

print(n2)
```

Running this multiple times shows that the paginator example finds a random number of tweets between 0 and 500 (seemingly always one of 0, 44, 400, 500, 200) while the non paginated example finds a random number of tweets between 0 and 100 (22, 100, 40).

The documentation doesn't mention anything about this at all so I feel it must be a bug but please correct me if this is intentional behaviour.

**Comment by Harmon758** [comment]
This is an eventual consistency issue with Twitter's API specific to this account, "elonmusk", and not an issue with Tweepy.
See #1550.

Note, the reason `n` returns up to 500 results rather than 250 is because `Paginator.flatten` is being used, so `responses` is a Tweet object each time. The length of the default Tweet data is 2 (`id` and `text`), so `n` is double the number of Tweets retrieved.
