### ISSUE TITLE
Tweepy  tweepy.api.API.rate_limit_status does not return rate limits for all objects OR does not return all of Twitter's rate limits .

### ISSUE THREAD

**Issue by ScarletMcLearn** [tweepy/tweepy#1739]
Cannot get rate limit status for all object using `tweepy.api.API.rate_limit_status` .

When I try to get resources for Tweepy's rate_limit_status it returns the following resources :
Code - `api.rate_limit_status()['resources'].keys()`

Output - 

> dict_keys(['lists', 'application', 'mutes', 'verify', 'admin_users', 'live_video_stream', 'friendships', 'guide', 'auth', 'compliance', 'paseto', 'blocks', 'geo', 'users', 'teams', 'followers', 'collections', 'permissions', 'tweets&POST', 'statuses', 'custom_profiles', 'webhooks', 'contacts', 'labs', 'i', 'tweet_prompts', 'moments', 'limiter_scalding_report_creation', 'fleets', 'help', 'feedback', 'business_experience', 'graphql&POST', 'friends', 'sandbox', 'drafts', 'direct_messages', 'media', 'traffic', 'strato', 'account_activity', 'account', 'safety', 'favorites', 'lists&POST', 'device', 'tweets', 'saved_searches', 'oauth', 'search', 'trends', 'live_pipeline', 'graphql'])

But I cant get rate limit for several objects as available in Twitters documentation:
[](https://developer.twitter.com/en/docs/twitter-api/rate-limits)

One such example is the rate limit for `API.create_friendship()`

Please suggest how I can get the rate limits for the missing resources / objects using Tweepy.

And please let me know if there is any alternatives available if not via Tweepy.

Thank you.

**Comment by Harmon758** [comment]
This is a Twitter API limitation:
> You may also issue requests to this method without any parameters to receive a map of all rate limited GET methods.

per the documentation for the [GET application/rate_limit_status endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/developer-utilities/rate-limit-status/api-reference/get-application-rate_limit_status) that `API.rate_limit_status` uses.

`API.create_friendship` is a POST endpoint/method.

If you only need the specific static rate limits for each endpoint/method, you can refer to the [Twitter API documentation for Standard v1.1 API rate limits](https://developer.twitter.com/en/docs/twitter-api/v1/rate-limits).

Otherwise, there's currently not a simple way to access the rate limit headers through Tweepy. #949 is a relevant issue about this.
