### ISSUE TITLE
How to post a tweet using tweepy?

### ISSUE THREAD

**Issue by yesdeepakmittal** [tweepy/tweepy#1770]
How can I post a tweet using API.update_status()? It needs POST permission but I did not find this app permission option on the Twitter Developer App page.

**Comment by realrodri** [comment]
You need to apply for the "Elevated" Twitter Developer program. It's free, you just need to submit a form and maybe a couple of emails due to Twitter's auto response, but then you should be good to go. I'd recommend then follow this steps:

First, install tweepy library (pip install tweepy).

Next, create a .py file containing this:

```
import tweepy
auth = tweepy.OAuthHandler("CONSUMER KEY HERE", "CONSUMER KEY SECRET HERE")
auth.set_access_token("ACCESS TOKEN HERE", "ACCESS TOKEN SECRET HERE")
api = tweepy.API(auth)
tweet = input(" ")
api.update_status(status =(tweet))
print ("Done!")
```

Your tweet should be live then.

**Comment by ByBilal** [comment]
> 

how am i able to post a tweet with only the essential account?

**Comment by Harmon758** [comment]
The OAuth 1.0a App permissions setting is under the User authentication settings section of the Settings tab of your developer portal's App page.
