### ISSUE TITLE
debug(False) enables debug

### ISSUE THREAD

**Issue by Paso** [tweepy/tweepy#1802]
tweepy.debug in `tweepy/__init__.py` ignores its enable argument which makes statements such as `tweepy.debug(args.VERBOSE >= 2)` not work as expected

**Comment by Harmon758** [comment]
This is a legacy function back from when the library directly used `httplib`.
Its `enable` parameter has actually been ignored [since it was added](https://github.com/tweepy/tweepy/commit/8440d31cc90c10adc5404d485c35b080c2ec711e).
Since it's undocumented and serves little purpose (You can easily set `http.client.HTTPConnection.debuglevel` yourself), I'll be removing it in the next release. Thanks for pointing it out.

Tweepy and its dependencies use [`logging`](https://docs.python.org/3/library/logging.html), so to control logging, you can instead use `logging.basicConfig` or use `logging.getLogger` to configure the logger for each library individually.

**Comment by Harmon758** [comment]
Resolved with https://github.com/tweepy/tweepy/commit/a702325c3b1cac98e6ea7c5b19bbdd56f8745cc2, where I've removed the `debug` function,
I've also added documentation for logging with https://github.com/tweepy/tweepy/commit/77015065f63022747eb10f6ed081b39dbc75c4a3. I opted not to include any mention of `http.client.HTTPConnection.debuglevel`, as it's constrained to only printing to the console and it doesn't seem to be explicitly documented in Python's documentation for the `http.client` module.
