### ISSUE TITLE
 discrepancy between pip version tweepy docs and github

### ISSUE THREAD

**Issue by bonomip** [tweepy/tweepy#1816]
pip show tweepy:

              Name: tweepy
              Version: 4.5.0
              Summary: Twitter library for Python
              Home-page: https://www.tweepy.org/
              Author: Joshua Roesslein
              Author-email: tweepy@googlegroups.com
              License: MIT

Parameters of Client.get_liking_users() and  Client.get_retweeters() functions are not the same of twitter api GET /2/tweets/:id/liking_users function. Neither on tweepy docs neither on the source code provided by pip despite on github are correct.

**Comment by Harmon758** [comment]
The master branch of this repository is the development version of the library. This is pretty standard.
See [the documentation on installation](https://tweepy.readthedocs.io/en/v4.5.0/install.html) for installing this version.

v4.5.0 is the latest release. Since then, new parameters were added to those methods with https://github.com/tweepy/tweepy/commit/bdd6b55d7cb075fc2e4c7cb56a061c552ca106fe and https://github.com/tweepy/tweepy/commit/3479e56a0fff02594ab6e77ca8227e65b51b46f7, respectively, after [the Twitter API recently added them to the endpoints they use](https://twittercommunity.com/t/updates-to-retweets-lookup-and-likes-lookup-endpoints/165327).

The [latest version of the documentation](https://tweepy.readthedocs.io/en/latest/) is correct and reflects this. You're likely looking at the documentation for v4.5.0.

These and other changes are set to be released with v4.6.0.
