### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'create_favorite'

### ISSUE THREAD

**Issue by andreasofthings** [tweepy/tweepy#1863]
Dear tweepy team,

when I implement a rather straight forward Stream, that filters for keywords, from documentation and examples I understand on_status will receive a Status model.

The implementation looks somewhat like this:

```
class StreamLiker(tweepy.Stream):

    def on_status(self, status):
        if not status.favorited:
            status.favorite()

stream = StreamLiker(
        args.consumer_key,
        args.consumer_secret,
        args.token,
        args.secret)

stream.filter(track=["some very relevant keyword"])
```

With 
 - Python 3.9.9
 - tweepy=04.8.0

the above produces this error:

```
Error on fav
Traceback (most recent call last):
  File "/Users/andreas/github/filterbubble/bubble.py", line 109, in on_status
    status.favorite()
  File "/Users/andreas/.pyenv/versions/3.9.9/lib/python3.9/site-packages/tweepy/models.py", line 375, in favorite
    return self._api.create_favorite(self.id)
AttributeError: 'NoneType' object has no attribute 'create_favorite'
```

having read the documentation and some of the code, I was expecting this should actually favourite the Status/Tweet. 
I hope I am not missing something obvious?

**Comment by Harmon758** [comment]
`Status.favorite` is an undocumented method that uses an undocumented attribute `_api`, which is assigned the instance of `API` that `Status` is from when its initialized.

`Status.favorite` won't work with `Stream`, because there is no instance of `API` to use when initializing the `Status` object, so the `_api` attribute is `None`.

Instead, you can simply initialize your own instance of [`API`](https://tweepy.readthedocs.io/en/v4.8.0/api.html#tweepy.API) and use [`API.create_favorite`](https://tweepy.readthedocs.io/en/v4.8.0/api.html#tweepy.API.create_favorite) yourself.

Since `Status.favorite` is an undocumented method and since there's not really a good way to handle this through `Status` and you can easily use your own instance of `API`, this won't be fixed.

**Comment by andreasofthings** [comment]
Thanks Harmon
