### ISSUE TITLE
Update api.search_tweets method to Twitter API V2 tweets/search to account for start_time and end_time

### ISSUE THREAD

**Issue by danielpartida** [tweepy/tweepy#1895]
The method implemented at Twitter API V2 https://developer.twitter.com/en/docs/twitter-api/tweets/search/api-reference/get-tweets-search-all takes into consideration "start_time" and "end_time". The older version (Twitter API V1 v) takes only into consideration "until" https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets

**Comment by Harmon758** [comment]
Since [`API`](https://tweepy.readthedocs.io/en/v4.9.0/api.html#tweepy.API) is Tweepy's interface with Twitter API v1.1, [`API.search_tweets`](https://tweepy.readthedocs.io/en/v4.9.0/api.html#tweepy.API.search_tweets) uses the Twitter API v1.1 endpoint you've linked. This is not something that is going to be changed. [`Client`](https://tweepy.readthedocs.io/en/v4.9.0/client.html#tweepy.Client) is Tweepy's interface with Twitter API v2, and [`Client.search_all_tweets`](https://tweepy.readthedocs.io/en/v4.9.0/client.html#tweepy.Client.search_all_tweets) uses the Twitter API v2 endpoint that you've linked.
