### ISSUE TITLE
search_all_tweets: Not getting full text despite API v2 if scraped tweets are retweets

### ISSUE THREAD

**Issue by lblind** [tweepy/tweepy#1915]
Hi guys,

I am scraping tweets per userid for the time period of a month via the method search_all_tweets  (https://docs.tweepy.org/en/stable/client.html#search-tweets )
I encountered a rather interesting issue/ phenomenon that might be a bug :
Some of the tweets I scraped have been truncated, as explained in: https://docs.tweepy.org/en/stable/extended_tweets.html .
However, I am using the API v2 Client, so I was assuming that this wouldn't happen. This is also the case for normal tweets, but not for retweets .
To be more specific, after a bit of debugging I figured that the tweets always fulfil these three conditions:

1) their tweet/ text length >= 140 (old twitter cap) (real length without (RT @[usernamelist], …) == 140)
2) they always end with the … character (suffix that indicates truncation)
3) they are retweets

Whilst 1) and 2) make sense to me, 3) indicates that in the backend still API v1 instead of API v2 is used.
If this is the case, I would suggest to maybe change that, or at least document it, as it seems a bit counterintuitive to me.

Also, am I right in my assumption that with the current implementation the only way to get the full/extended tweet text is by running the requests again via API v1 (not v2) and setting the extended parameter?

**Comment by Harmon758** [comment]
Retweets are truncated in both Twitter API v1.1 and v2.
This is a limitation of Twitter's API and not a bug with Tweepy.

Tweepy's interface for Twitter API v2 is `Client`, and its interface for Twitter API v1.1 is `API`.
`Client` does not use Twitter API v1.1 in any way (and `API` does not use Twitter API v2 in any way).
If you're only using `Client`, then you're not using Twitter API v1.1 at all.

You can use the `referenced_tweets.id` [expansion](https://tweepy.readthedocs.io/en/v4.10.0/expansions_and_fields.html#expansions) to retrieve the Tweet object representing the Tweet being Retweeted (and its text).

> This is also the case for normal tweets, but not for retweets .

I'm not sure you mean this, as it doesn't match any other information you've provided, but if you're encountering truncated Tweets (that aren't Retweets), rather than Retweets, you'll need to provide a reproducible example (MCVE/SSCCE) of this.

**Comment by lblind** [comment]
> Retweets are truncated in both Twitter API v1.1 and v2. This is a limitation of Twitter's API and not a bug with Tweepy.
> 
> Tweepy's interface for Twitter API v2 is `Client`, and its interface for Twitter API v1.1 is `API`. `Client` does not use Twitter API v1.1 in any way (and `API` does not use Twitter API v2 in any way). If you're only using `Client`, then you're not using Twitter API v1.1 at all.
> 
> You can use the `referenced_tweets.id` [expansion](https://tweepy.readthedocs.io/en/v4.10.0/expansions_and_fields.html#expansions) to retrieve the Tweet object representing the Tweet being Retweeted (and its text).
> 
> > This is also the case for normal tweets, but not for retweets .
> 
> I'm not sure you mean this, as it doesn't match any other information you've provided, but if you're encountering truncated Tweets (that aren't Retweets), rather than Retweets, you'll need to provide a reproducible example (MCVE/SSCCE) of this.

Thank you so much for clarifying this and your support! I wasn't aware of this Twitter API limitation still existing in API v2 (for retweets).
Yes, I am purely operating via API v2/  `Client` .
And this limitation only applies to retweets, the truncation is as expected, e.g.: `RT @someusername: Some truncated tweet text ending ju…` . 
So I think to retrieve the untruncated retweeted tweet, I will work via the `referenced_tweets.id` expansion as you suggested.
Thanks again!
