### ISSUE TITLE
Issue using Pagination reverse flag on search_recent_tweets

### ISSUE THREAD

**Issue by dtaivpp** [tweepy/tweepy#1926]
Hey all, I am not sure if I am missing something but when I am running pagination with the reversed flag the number of results I receive is dramatically different than when I run it without the flag. 

```python
cl = tweepy.Client(bearer_token=token)
tweets = tweepy.Paginator(cl.search_recent_tweets,  
                                "OpenSearch",
                                tweet_fields=['id', 'author_id', 'text', 'lang', 'public_metrics', 'created_at', 'entities'],
                                expansions=['author_id', 'referenced_tweets.id'], 
                                user_fields=['username'],
                                max_results=40,
                                since_id=None)

all_tweets = []
for tweet_page in tweets:
    for tweet in tweet_page.data
        all_tweets.append(normalize_tweet(tweet))
```

When I run the above with `reversed = True` at the moment I get exactly 80 results (2 iterations). Without the reversed flag I receive ~460 results.

**Comment by Harmon758** [comment]
If you're referring to the `reverse` parameter for `PaginationIterator`, that's used for paginating backwards. It would be expected that passing it as `True` to `Paginator` without a pagination token would only return a single iteration/response, since that would be the first page with nothing to paginate backwards to, and that is the behavior I'm seeing:
```pycon
>>> responses = tweepy.Paginator(
...     client.search_recent_tweets,
...     "OpenSearch",
...     tweet_fields=[
...         'id', 'author_id', 'text', 'lang', 'public_metrics', 'created_at',
...         'entities'
...     ],
...     expansions=['author_id', 'referenced_tweets.id'],
...     user_fields=['username'],
...     max_results=40,
...     since_id=None,
...     reverse=True
... )
>>> len(list(responses))
1
```
I'm encountering the same expected behavior when using the Python built-in `reversed` function:
```pycon
>>> responses = tweepy.Paginator(
...     client.search_recent_tweets,
...     "OpenSearch",
...     tweet_fields=[
...         'id', 'author_id', 'text', 'lang', 'public_metrics', 'created_at',
...         'entities'
...     ],
...     expansions=['author_id', 'referenced_tweets.id'],
...     user_fields=['username'],
...     max_results=40,
...     since_id=None
... )
>>> len(list(reversed(responses)))
1
```
I'm unable to reproduce 2 iterations/responses being returned.

Otherwise, I'm not sure what "reversed flag" you're referring to, as there is no `reversed` parameter anywhere in Tweepy, and I'm pretty sure there's not a `reversed` parameter for any Twitter API endpoints either (and definitely not for the recent search endpoint).

Do you have a reproducible example (MCVE/SSCCE) of what exactly you're trying and encountering?
