### ISSUE TITLE
Change function names to be more intuitive

### ISSUE THREAD

**Issue by Yadnyawalkya** [tweepy/tweepy#1976]
Can we use `get_following_ids` instead of `get_friend_ids`? Should we replace `friend` with `following` in tweepy functions?

For instance, the current `get_friend_ids` or `get_friends` functions aren't intuitive since everyone I follow isn't my friend. It took me a while to find the correct function and I only found it after reading tweepy API documentation.

As we are already using `get_follower_ids`, why not use `get_following_ids` too; which is how also twitter refer to.

**Comment by Harmon758** [comment]
`API.get_friend_ids` is named after the Twitter API endpoint it uses, [GET friends/ids](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-ids). Other `API` methods with "friend" in their names are similarly named after the Twitter API endpoints that they use, e.g. `API.get_friends` uses [GET friends/list](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/follow-search-get-users/api-reference/get-friends-list).

These are old methods and endpoints, but the Twitter API documentation for those endpoints does still refer to users being followed as "friends" as well, beyond in the endpoint path, e.g. in the documentation for GET friends/ids.

Renaming them now would be a breaking change, after over 13 years, that would differentiate from, rather than more closely match, Twitter's API.

**Comment by Yadnyawalkya** [comment]
Thank you for explanation @Harmon758.
