### ISSUE TITLE
Client.get_tweet() doesn't return fields data

### ISSUE THREAD

**Issue by isaswa** [tweepy/tweepy#2015]
I tried searching on stackoverflow but there seems to be no example with tweepy v4.
I also checked the doc about this problem:
https://docs.tweepy.org/en/v4.6.0/faq.html#why-am-i-not-getting-expansions-or-fields-data-with-api-v2-using-client

when I tried the codes below:
```py
print(client.get_tweet(id=id, media_fields=['url']))
print(client.get_tweet(id=id, media_fields=['url']).includes)
print(client.get_tweet(id=id, media_fields=['url']).includes['url'])
```
all of them printed out empty `includes` fields
the last line raised the error `KeyError: url`, which means the function does not actually return the fields I ask for.

**Comment by Harmon758** [comment]
There is an [Examples](https://tweepy.readthedocs.io/en/v4.12.1/examples.html) page in the documentation.

`Response.includes` returns objects requested through [expansions](https://tweepy.readthedocs.io/en/v4.12.1/expansions_and_fields.html#expansions).
You aren't requesting any expansions, so `Response.includes` is an empty dictionary as expected.

Without expansions, there are no media objects for that Twitter API endpoint to return, since it provides Tweets,  so there are no media objects for which to return the single `url` field that you are requesting.
