### ISSUE TITLE
Stream using v2 API

### ISSUE THREAD

**Issue by flxai** [tweepy/tweepy#2062]
Hello and thanks for this project,

reading Tweepy's [docs on streaming](https://docs.tweepy.org/en/stable/streaming.html), it seems to me that this only allows for usage of Twitter's v1 API, since it requires the user to provide a consumer key, consumer secret, access token and access token secret. Is it possible or planned to be able to use Twitter's new v2 API to use filtered streaming in Tweepy?

**Comment by flxai** [comment]
Seems like Tweepy is already capable of this, using [`tweepy.StreamingClient.filter`](https://docs.tweepy.org/en/stable/streamingclient.html#tweepy.StreamingClient.filter):

> Filter and sample realtime Tweets with Twitter API v2

While usage appears to be self-explanatory, it seems that proper documentation is still lacking.

**Comment by Harmon758** [comment]
Tweepy has supported streaming with Twitter API v2, with `StreamingClient`, since [v4.6.0](https://github.com/tweepy/tweepy/releases/tag/v4.6.0), which was released almost a year ago.

Usage of `StreamingClient` is fully and specifically documented in [an entire section of the documentation page that you linked](https://tweepy.readthedocs.io/en/v4.12.1/streaming.html#using-streamingclient).
