### ISSUE TITLE
Refactor lookup functions names

### ISSUE THREAD

**Issue by chimeno** [tweepy/tweepy#477]
Currently there are at least three function for lookup bulk data: `statuses`, `friendship` and `users`.
Meanwhile two of them are called: `lookup_friendship`and `lookup_users` the other one is called `statuses_lookup`. [code](https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L86).
I think is a good idea having all three in the same way, although we can fall in backward incompatibility, unless we proved a fallback.

Just saying.

**Comment by teoguso** [comment]
Hello everyone,
I write here because my issue might be related to this. If not just let me know and I will open a separate one.
the api method `lookup_users()` is currently not documented, or not that I am aware. I am looking at the docs for 3.6. Given that it's possibly the fastest way to retrieve full user information for many users,  it would be a pity if it went missing for those who don't have time to dig deep enough. Does it make sense?

**Comment by Harmon758** [comment]
@teoguso This is unrelated. See #539.
