### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OAuthHandler'

### ISSUE THREAD

**Issue by panoptikum** [tweepy/tweepy#490]
Dear Tweepy Team,

I'm keep running into this error and I'm really frustrated. Have I installed it correctly? Or where could this error come from? I have no clue:

> > > auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > AttributeError: 'module' object has no attribute 'OAuthHandler'

Any advice is appreciated!

Kind regards

**Comment by varunjain97** [comment]
Dear Tweepy Team,
when i am runing **from tweepy.auth import OAuthHandler**  then i got an error please debug it
this is my error
'path' must be None or a list, not <class '_frozen_importlib_external._NamespacePath'>

**Comment by MVL10** [comment]
Dear Team,

I am facing the error like this 
auth.set_access_token(config.access_token, config.access_secret)
AttributeError: 'module' object has no attribute 'access_token'
and I tried all the above suggestions. Still, I am facing the same issue. So please can anyone help me out:)

**Comment by MVL10** [comment]
Dear Tweepy Team,

I keep running into this error and I'm really frustrated. Have I installed it correctly? Or where could this error come from? I have no clue:

auth.set_access_token(config.access_token, config.access_secret)
AttributeError: 'module' object has no attribute 'access_token'
 
Any Advice is Appreciated

**Comment by zackxo** [comment]
its an O.

**Comment by Harmon758** [comment]
Note, as previously stated, this issue was fixed with https://github.com/tweepy/tweepy/commit/d9d5a8648d738c660fc0a457523d0083d03c2353 as part of v3.0.0.

@varunjain97 That is not related to this issue and doesn't even seem to be related to this library.
A cursory scan of the results for a quick search for that error seems to point to it being [an issue with Spyder](https://github.com/spyder-ide/spyder/issues/5299).

@MVL10 This is not related to this issue and is not an issue with the library.
This is an error in your project configuration. Make sure that you're exposing the `access_token` in your `config` module.
