### ISSUE TITLE
pip version 6.0 changed the method signature for `pip.req.parse_requirements`.

### ISSUE THREAD

**Issue by d0ugal** [tweepy/tweepy#533]
This means that the setup.py fails with something like:

    File "/tmp/pip-build-3xmp1q/tweepy/setup.py", line 18, in <module>
        reqs = [str(req.req) for req in install_reqs]
      File "/home/dougalmatthews/.virtualenvs/tmp-e9ea5ec74c214e7c/lib/python2.7/site-packages/pip/req/req_file.py", line 19, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'

**Comment by d0ugal** [comment]
This appears to have been fixed by https://github.com/tweepy/tweepy/commit/9b4cb9eb123be05a925c1c6deaf0141699853644

**Comment by jmagnusson** [comment]
When will we see a new release with this fix? The regression kills some packages...

**Comment by AeroNotix** [comment]
Why did you use a uuid?

**Comment by mw44118** [comment]
What is the session for?
And if it's a required parameter, why do you give it a default of None?  That's crazy.

**Comment by AeroNotix** [comment]
Passing a UUID is just dumb and is cargo-culting.

**Comment by d0ugal** [comment]
If you want to comment on the change, this isn't the place to do it. Do it on the commit (https://github.com/tweepy/tweepy/commit/9b4cb9eb123be05a925c1c6deaf0141699853644) or somewhere the author will see it.

**Comment by skruger** [comment]
I just ran into this in another project.  I discovered that the session= kwarg is passed an instance of PipSession() when this function is invoked using the pip command line.  It is eventually used in pip.download.get_file_content():396 where its get() method is invoked.

**Comment by NiklasRosenstein** [comment]
> And if it's a required parameter, why do you give it a default of None? That's crazy.

I am wondering about this, too.

**Comment by Harmon758** [comment]
The fix for this was merged from #534, which uses [a hack](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py/16624700#16624700).
The issue was caused by [a change](https://github.com/pypa/pip/commit/7037443975ee5706ef829f14a52ac2fba7dbfff2) (https://github.com/pypa/pip/pull/1796) in pip 6.0 that required an HTTP session to be passed even if there weren't any external references by URL to resolve. The hack was just to pass anything as the session, so as not to trigger any `is None` checks, since session would not be used. However, I'm not sure why the author of #534 chose to unnecessarily use a UUID.
Nevertheless, due to [a change](https://github.com/pypa/pip/commit/95bcf8c5f6394298035a7332c441868f3b0169f4#diff-851cc85103a872db421c81afadd4fee5) (https://github.com/pypa/pip/pull/4700) in pip 10.0.0 (see #1029) and the resulting fix by https://github.com/tweepy/tweepy/commit/29e32cdf4a67b1fca25dbf04d7b8069ac1c9dd0d (#1030) in [3.7.0](https://github.com/tweepy/tweepy/releases/tag/3.7.0), this should no longer be a relevant issue.
