### ISSUE TITLE
search() method isn't working: module called by Tweepy being passed a generator object where string was expected

### ISSUE THREAD

**Issue by tstirrat15** [tweepy/tweepy#544]
Preface: I can't tell where this issue lies: my connection to and account with the API, my code, or an issue with Tweepy.

I'm trying to execute a search and receiving an error several layers deep. Here's a pastebin including the code I'm using and the full trace of the error:

http://pastebin.com/9he4Ddc0

**Comment by tstirrat15** [comment]
More information:

I'm running tweepy in a dedicated virtualenv, and have selected 3.4 as the python version for the environment.

I've tried other methods in the API as well:
 - `verify_credentials()`
 - `get_user()`
 - `followers_ids()`
all throw the same error.

Interestingly, when I try to run `trends()`, I get an error saying that the method doesn't exist, despite it existing in the documentation.

Could there be something else going on?

**Comment by Harmon758** [comment]
One or more of your credentials that you're importing are generator objects instead of strings.

`API.trends` was deprecated and removed with https://github.com/tweepy/tweepy/commit/e323190a4f2642b3b91b05161e1700e72e0731f7 in Tweepy 1.12, and the documentation was removed with https://github.com/tweepy/tweepy/commit/cbcb62f251ff64626d940cb3d29fc5ea76494f5a in Tweepy v3.2.0.
