### ISSUE TITLE
Converting to exe

### ISSUE THREAD

**Issue by folsomee** [tweepy/tweepy#555]
I have a Main.py file that works well when I run it from IDLE. However I'm not able to convert it to a exe file using py2exe.

Below is the setup.py code:

import tweepy
from distutils.core import setup
import py2exe

setup(
    windows = [{"script": "main.py"}],
    options = {"py2exe":{"includes":["tweepy"]}}
    )

When I try to convert , I get the following error:
ImportError: No module named tweepy

Has anyone faced this issue?

**Comment by AwolDes** [comment]
@folsomee I'm getting hit with this error right now, did you end up fixing it? I've got basically the same code as you do.

**Comment by folsomee** [comment]
No, I have not been able to convert this to an exe yet.

**Comment by AwolDes** [comment]
Damn, well I'll let you know if I figure it out!

**Comment by folsomee** [comment]
Yes please do let me know!

**Comment by ductri** [comment]
I get the same error: No module name six

**Comment by Harmon758** [comment]
Tweepy is a package rather than a module, so according to [py2exe's documentation](http://www.py2exe.org/index.cgi/ListOfOptions), you'll want to specify it using the `packages` key rather than the `includes` key. (@ductri This also applies to six)

This is not an issue with Tweepy.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python or py2exe.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
