### ISSUE TITLE
TweepError: Failed to send request: data must be a byte string

### ISSUE THREAD

**Issue by DavidBrowne1** [tweepy/tweepy#573]
Hi All,

I am getting the above error and am unsure why? The code works on another pc but not mine.
Is there some packages I am missing?
Thanks

from tweepy import Stream
from tweepy import OAuthHandler
from tweepy.streaming import StreamListener
# consumer key, consumer secret, access token, access secret.

ckey = xx
csecret = xx
atoken = xx
asecret = xx

class listener(StreamListener):

```
def on_data(self, data):        
    print(data)
    return(True)

def on_error(self, status):
    print status
```

auth = OAuthHandler(ckey, csecret)
auth.set_access_token(atoken, asecret)

twitterStream = Stream(auth, listener())
twitterStream.filter(track=['cars'])

**Comment by syndbg** [comment]
`return(True)`

you meant `return True` ?

**Comment by DavidBrowne1** [comment]
@syndbg Yes return true
It seems to be an authorisation error. 
My code works on a pc in college but not at home?
It is really confusing me

**Comment by syndbg** [comment]
@DavidBrowne1 

Try adding `auth.set_secure = True`.

```
auth = OAuthHandler(ckey, csecret)
auth.set_secure = True
auth.set_access_token(atoken, asecret)
```

If the above fails, could you try getting filtered results using the https://dev.twitter.com/rest/tools/console

**Comment by pg1671** [comment]
I had this problem appear a few days ago with no code changes and I tracked it down to being the ndg-httpsclient library.  I was having problems with SSL on a certain site and someone suggested installing requests with the requests[security] option which fixed my SSL problem and installed this library.  Another post suggested the actual problem is PyOpenSSL which is a dependancy.

Once I removed ndg-httpsclient the error went away but my other problem will have returned but prefer my twitter integration to be working for now.

The error occurred in a call to _lookup_users()

**Comment by Karlheinzniebuhr** [comment]
same issue here

**Comment by wikier** [comment]
no progress on this issue...?

**Comment by Harmon758** [comment]
I'm unable to reproduce this, and it seems to be an issue with SSL, pyOpenSSL, and/or requests.
For this issue to be actionable, a full traceback is needed from the exception caught here:
https://github.com/tweepy/tweepy/blob/51f680c27af5bc55cde2688cb0ef7b5e0b05c38f/tweepy/binder.py#L188-L189  Additionally, since this is very likely a dependency issue, the specific versions of Python, Tweepy, and requests this occurs with needs to be provided.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

@syndbg `return(True)` is not invalid, and `OAuthHandler.secure` was removed with https://github.com/tweepy/tweepy/commit/4de7333c78bf422a1b0c66511536aaf3aa8cb652 as part of Tweepy v3.0.0.
