### ISSUE TITLE
Support video upload

### ISSUE THREAD

**Issue by dougppaz** [tweepy/tweepy#640]
I read this post on twitter blogs:
https://blog.twitter.com/2015/rest-api-now-supports-native-video-upload

And i would like know if now is possible post videos on twitter via tweepy?!

**Comment by PierrickFil** [comment]
According to Twitter Dev docs, we need to use the https://dev.twitter.com/rest/reference/post/media/upload-chunked endpoint following the following implementation https://dev.twitter.com/rest/public/uploading-media#chunkedupload

Nothing in the code for now, hope this will coming quickly.

**Comment by askaliuk** [comment]
https://github.com/tweepy/tweepy/pull/655

**Comment by Harmon758** [comment]
I'd like to try to get #929 into Tweepy v3.9 or v4.0, depending on how quickly the review process can be completed.

cc @fitnr re:#1180

**Comment by fitnr** [comment]
@Harmon758 #929 is a good commit, I've been using it in production for almost 2 years. Let me know if I can assist with the review in any way.

**Comment by WaliyaYohannaJoseph** [comment]
How can I gather tweet data using tweet just for one month's post from @Protestitas

**Comment by Harmon758** [comment]
@WaliyaYohannaJoseph That's not related to this issue at all.
See https://tweepy.readthedocs.io/en/latest/api.html#API.user_timeline and https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.

**Comment by MuhBayu** [comment]
Hi, I get the same error

> Invalid file type for image: video/mp4

I use version 3.8.0 of Tweepy
is there any solution?

**Comment by metehus** [comment]
> Hi, I get the same error
> 
> > Invalid file type for image: video/mp4
> 
> I use version 3.8.0 of Tweepy
> is there any solution?

I can agree. I'm also receiving this error

**Comment by PedroDaumas** [comment]
Hey, I would just like to emphasize the desire to see PR #929 merged. 
I would like to use it in an ongoing project and would appreciate any updates

**Comment by Harmon758** [comment]
v3.9.0 was released without this feature. I had intended to try to release it with v3.9.0.
I've since fixed and improved the [changelog](https://github.com/tweepy/tweepy/blob/master/CHANGELOG.md#version-390) and [release notes](https://github.com/tweepy/tweepy/releases/tag/v3.9.0) for v3.9.0.
Since v3.9.0 was also released without originally noting that it would be the last version to support Python 2 (#1253) in its changelog and release notes, a v3.10.0 is now planned for that and the goal is to include this in that release.
I've updated the milestones accordingly, but this might still be pushed back to v4.0, as I'd like to get started on dropping Python 2 support sooner rather than later.

**Comment by jackyliang** [comment]
Any ETA on when v4.0.0 is being released :)? Really looking forward to using this feature!

**Comment by Harmon758** [comment]
The goal is still to include this in v3.10.0, which will be released prior to and likely a lot sooner than v4.0.
You can check the milestones for both to see what still needs to be done for each version.

@fitnr #929 seems to be stale now. I wouldn't be adverse to a new updated PR from you that includes the original commits from #929 as well as the further improvements you made that haven't been included in it yet. If you're up for it, you'd also need to address the issues in my review of #929 though. Otherwise, I'll probably create a new branch and PR to do so myself (I'd still include the original commits and probably the additional improvements you made as well), but in that case, it'll be more likely that I drop Python 2 support for it and push it back to v4.0.

**Comment by fitnr** [comment]
@Harmon758 I can work on a revised pull incorporating your notes.

**Comment by asarra** [comment]
What is the issue with this video upload thingy not being implemented for many years while such pulls already do exist?
Not trying to sound rude and I understand that everyone has a private life, but come on... 5 years, you gotta be kidding me

**Comment by Harmon758** [comment]
I'm pushing this back to v4.0.
See https://github.com/tweepy/tweepy/pull/1414#pullrequestreview-558777740 for further explanation.

**Comment by Harmon758** [comment]
The video-upload branch / pull request #1486 should be complete now.
Any feedback or review would be appreciated.

**Comment by layilpaht** [comment]
@Harmon758 Hi. Is now Video upload feature working? If yes then how to do it (or link to any such instructions?)
Thanks In Advance

**Comment by Harmon758** [comment]
#1486 has just been merged, so it should be working with the development version on the master branch.
For installation, see https://tweepy.readthedocs.io/en/latest/install.html and https://pip.pypa.io/en/stable/reference/pip_install/#git.
