### ISSUE TITLE
406 on Filter stream

### ISSUE THREAD

**Issue by makopov** [tweepy/tweepy#646]
I'm trying to stream data from Twitter using a filter like so: 

`self.oStream.filter(track=['nfl', 'broncos', 'patriots', 'seahawks'], async=True)`

(Avoided pasting the setup code)

The call works fine on my local laptop (Mac Yosemite), however when I push the code to digital ocean vm running Ubuntu 14.04 LTS I get a 406 error code in responce, both my Mac and the server run Python 2.7.6.

I am literally running the same code locally as I do on Digital Ocean so I'm not certain why one would return a 406 and the other would return intended results. I went as far as pulling down the code from DO and doing a diff, there was no difference.

Any idea what might be going on here?

**Comment by Harmon758** [comment]
This isn't reproducible and fairly stale at this point.
The only other considerations might be different Tweepy versions, the server mangling the request somehow, or the API specifically rejecting the request from that server and responding with a 406 error code for some reason.
It's unlikely to be an issue with Tweepy itself, since your code runs locally, but feel free to create a new issue if you have a reproducible example (MCVE/SSCCE) of this using the latest development version of Tweepy.
