### ISSUE TITLE
"list index out of range"

### ISSUE THREAD

**Issue by meereeum** [tweepy/tweepy#669]
```
Exception: list index out of range
Traceback (most recent call last):
  File "bot.py", line 155, in <module>
    listen()
  File "bot.py", line 145, in listen
    stream.userstream(_with='user')
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 379, in userstream
    self._start(async)
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 346, in _start
    self._run()
  File "/Library/Python/2.7/site-packages/tweepy/streaming.py", line 286, in _run
    raise exception
IndexError: list index out of range
```

Unable to find bug in our implementation of StreamListener, so I could be wrong but this seems to be a Tweepy error ?

**Comment by johnkw** [comment]
Probably, but you'll need to provide more information on the exact tweepy version that had this problem.

**Comment by meereeum** [comment]
Good point... v3.4.0

**Comment by johnkw** [comment]
Looks like that could be an error in your code, but tweepy's not reporting it well. Not sure. (I can't use that version of tweepy at all due to the blocker bug #620.)

**Comment by meereeum** [comment]
Have not been able to pinpoint any lists in our code that it could possibly be referencing, but of course we might be missing something.

**Comment by Harmon758** [comment]
This issue is now stale, since User streams have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.
Feel free to create a new issue if you're able to reproduce this using another type of stream that's currently supported.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
