### ISSUE TITLE
Can someone find the fault in this small piece of code?

### ISSUE THREAD

**Issue by revanthrr** [tweepy/tweepy#673]
So what i'm trying to do is take a sample tweet, and follow the recent 20 people who retweeted that tweet

import tweepy

consumer_key = 'XXXXXXXXXXXXXXXXXXXXXX'
consumer_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
access_token = '624837175-XXXXXXXXXXXXXXXXXXX'
access_token_secret = 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

retwts = api.retweets(id=665594047684300800, count=20)

for status in retwts
api.create_friendship(id=retwts)

I'm very new to programming sorry if that code was dumb but that was the best i could do by reading the docs, and it obviously isn't working. Can someone tell me where is the problem?

This is the error:-

File "tweepybot.py", line
for status in retwts
^
SyntaxError: invalid syntax

Thank you in advance.

**Comment by fitnr** [comment]
For the syntax, make sure to end `for` statements with a colon, then indent the next lines. Also, within the indented part, you'll need to use the loop variable (`status`), rather than the list (`retwts`) you're looping over. Finally, the `id` argument must be given the id of the user:
````python
for status in retwts:
    api.create_friendship(id=status.user.id)
````

If you have more problems, [Stack Overflow](http://stackoverflow.com/questions/tagged/python) is a good place for questions.

**Comment by revanthrr** [comment]
Dude, thank you so much, since i self taught myself python, this small thing was bugging me to death i stayed up till 5 AM, this helped me a LOT! Thanks again!

**Comment by timkofu** [comment]
Also read the [**entire** official Python tutorial](https://docs.python.org/3/tutorial/) if you haven't already.

**Comment by johnkw** [comment]
This isn't a tweepy issue - please mark this closed.
