### ISSUE TITLE
Silent fail / on_data not returning data

### ISSUE THREAD

**Issue by forstmeier** [tweepy/tweepy#678]
Hi - I'm trying to build a stream listener that will respond to direct messages from an account that is both followed/a follower, however, the on_data method does not appear to be returning data that can be parsed/acted upon by the rest of the script. I've tried both overriding the method and using the super method. The follow argument in the filter method would be the Twitter id (as a string) for my personal twitter account (the script waits for a specific text from my account and then does other stuff).

import tweepy
import json

CON_KEY = "###"
CON_SEC = "###"
ACC_TOK = "###"
ACC_SEC = "###"

auth = tweepy.auth.OAuthHandler(CON_KEY, CON_SEC)
auth.set_access_token(ACC_TOK, ACC_SEC)
api = tweepy.API(auth_handler=auth)

class FirstStream(tweepy.StreamListener):
        def on_data(self, data):
            super().on_data(data)
            json_data = json.loads(data)
            print(json_data['text'])
            return True

fs = FirstStream
aStream = tweepy.streaming.Stream(auth=api.auth, listener=fs())
aStream.filter(follow=['###'], track=['#python'])

**Comment by forstmeier** [comment]
P.S. One other thing that seems to be a problem is that I keep my account set to "private" - however taking off this setting does not prompt the rest of the script to run on receiving a direct message from my account.

**Comment by jeremylow** [comment]
You cannot follow a protected account in this manner. See: https://dev.twitter.com/streaming/overview/request-parameters#follow

However, if you want to follow a protected account, you can have the program run with the access key and secret attached to the protected account and use the `aStream.userstream()` method instead. This will return data for any tweets from that account. You can optionally set it to track whatever you like, but it will essentially only be listening to the one account.

Re: direct messages. Make sure you have the proper permissions for the application you're using, though I think this is solved by change referenced above.

**Comment by forstmeier** [comment]
I adjusted the last line to `aStream.userstream(_with=['###'], track=['#gameon'])` and while it will now print results, it does so regardless of whether "#gameon" is present in the Tweet. As a side note, the userstream appears to allow me to see the tweets of even a protected account although the direct messages are not visible.

**Comment by Harmon758** [comment]
This issue is now stale, since User streams have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
