### ISSUE TITLE
[UnicodeEncodeError] Platform or Python version related bug?

### ISSUE THREAD

**Issue by MrHohn** [tweepy/tweepy#721]
Hello all,

I just began using tweepy, but ran into a bug while following the Hello Tweepy example. Below is the code I used:

`
user = api.get_user("BarackObama")

private_tweets = user.timeline(count=200, include_rts=False)
for tweet in private_tweets:
    print(tweet.text)
`

About tens tweets were printed out normally and after this error came out:

Traceback (most recent call last):
  File "HelloTweepy.py", line 36, in <module>
    print(tweet.text)
UnicodeEncodeError: 'gbk' codec can't encode character '\u2714' in position 30: illegal multibyte sequence

Python version: 3.4.2
Operating System: WIN8.1

Thanks!

**Comment by MrHohn** [comment]
I then used print(tweet.text.encode("utf-8")) to gain the content. Is this what I suppose to do?

**Comment by elad661** [comment]
Python 3 has a very inconsistent UTF-8 behaviour that varies according to the system locale, as shown in this example:

https://gist.github.com/Spindel/8b2f2b5bbba10c93ca18

When your system locale is set to something that is not UTF-8, python will use that as a default for all strings instead of UTF-8.

Your options are either using a workaround (like shown here https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows ), or setting your system locale to UTF-8 , or dealing with .encode() and .decode() to utf-8 explicitly in your code.

**Comment by MrHohn** [comment]
Hi elad661,

Thanks for addressing the issue! You should be right that this problem is system locale related.

I try to adopt your second solution that changing my system locale setup, but seems like it does not work (may be still something to do with the Windows console). Anyway, I will work around this issue with .encode().

Since things are clear now, I'm closing this issue.
