### ISSUE TITLE
Tweepy / show.friendhips / example hint

### ISSUE THREAD

**Issue by Cypher92** [tweepy/tweepy#722]
Hi everybody,

I am a newbie in Python and I am using tweepy for my master thesis (I am a marketing management student). I am trying to get the friendhips relationships bewteen two twitter users ( companies in my case), but I can't figure out how to make this api method works.

I would like to retrieve a simple 0,1 results where 0 = "not following" and 1 ="following". 

this is my code just for the part I am interested in:

if api.show_friendship(source_screen_name='amazon', target_screen_name='eBay'):
    print ('1')
else:
    print ('0')

Any hint or Examples you can provide to me for this??? Please if possibile make it simple for me :))

THANKS!

**Comment by py3in** [comment]
hi @Cypher92 
about: "Any hint or Examples you can provide to me for this??? Please if possibile make it simple for me :))" 

I'm getting started on learning libweave and I made this example to also learn something. I do not know if it will help because it has been many months. Anyway, I hope it will be helpful to someone. 

my code test 

file with IDs accounts example: ns.txt 
------------------------------------------
1429451635
1439301337
1486427328
151560635
1705903454
181962719
182969683
187606791
190417964
1908943021
197642014
209789907
211779341
2157539166
2169386418
2176499716
2213085224
2280174352
2281774421
2330163656
2358073814
2380612423
2413968027
2429234718
2497409995
2592042930
-------------------------------------
This ID file will be used to get true or false to see if it is a friend or not.

====================================================
#! /usr/bin/env python
# -*- coding: utf-8 -*-

import time
import tweepy


consumer_key          = your consumer key'
consumer_secret       = 'your consumer secret'
access_token          = 'your acess token'
access_token_secret   = 'your token secret'
screen_name           = 'YourScreenName' # No used
id_account            = '983575464' # You ID. Not It's obligatory to be yours.
# To compare followers, any user X can be any user.

# starting acess
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

# I'm learning to use limit protection on code. 
# But to avoid errors, I'm activating the rate limit to have extra protection. 
# The tweepy lib does not let you pop the limit if it leaves true. 
# Require a security break to wait for a new reset.
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True, compression=True)

# If you want to use a fixed account to make the comparison, 
# uncomment the line below to avoid error in the test.
# id_account='id_existing'
# target_f='id_existing'

# Here you can already do a functional test using the two variables set above.
b = api.show_friendship(source_id=id_account,target_id=target_f)
print b # print status followers e friend about ids.

# If you want to stop the test here, uncomment the line below.
# exit()

# If you do not want to be ALWAYS comparing different ids accounts, 
# you can only use the varying target. 
# The tweepy lib will assume the screen_name and account ID 
# logged in now in the token.
#b = api.show_friendship(target_id=target_f)

# This variable receives all rate limits.
data = api.rate_limit_status()

# Just for learning, I am writing to file the position 
# of all the types of status and limits returned by the twitter api.
arq = open("limit_status.txt", "wb")

# My test with resources of api
for recursos in data['resources']:
	#print recursos
	tipo_recursos = data['resources'][recursos]
	#print tipo_recursos
	for o_recurso in tipo_recursos:
		#print o_recurso
		os_recursos = data['resources'][recursos][o_recurso]
		for os_limites in os_recursos: 
			#print os_limites
			time_limites = data['resources'][recursos][o_recurso][os_limites]
			mm = "data['resources']['"+\
				str(recursos)+"']['"+\
				str(o_recurso)+"']['"+\
				str(os_limites)+"']"
			#print str(time_limites)
			#print eval(mm)
			mm2 = mm + str(time_limites)
			#print mm 
			arq.write(str(mm2))
			arq.write("\n")

arq.close()

#exit()

# Consult file limit_status.txt To see all types of status and limits of api
# This is a pog for my learning.

# Below the limits fields for when you want to know about friends and followers
u = data['resources']['friendships']['/friendships/show']['remaining']
l = data['resources']['friendships']['/friendships/show']['limit']
t = data['resources']['friendships']['/friendships/show']['reset']
minutos = (t - time.time()) / 60
Usado = l - u
print u
print l
print t

T = 0

# For test 
while T < 190:
	with open('ns.txt') as fp:
		for target_f in fp:
			b = api.show_friendship(source_id=id_account,target_id=target_f)
			print "Estou seguindo ? " + str(b[1].followed_by) # If false I do not follow. 
			print "Está me seguindo ? " + str(b[1].following) # If True, He is following me. 
			data = api.rate_limit_status()
			u = data['resources']['friendships']['/friendships/show']['remaining']
			l = data['resources']['friendships']['/friendships/show']['limit']
			t = data['resources']['friendships']['/friendships/show']['reset']
			minutos = (t - time.time()) / 60
			Usado = l - u
			print "Usou..." + str(Usado) +\
			". Faltam " + str(u) +\
			" pra usar em " +\
			str(minutos) +\
				" minutos"
			T = T + 1
			if u < 3 or minutos < 2:
				# Quer dizer que vou ter que descansar.
				print "Vou esperar por " + str(minutos) + " minutos pra voltar..."
				espera = minutos * 61
				print espera / 60
				time.sleep(espera)



exit()

# This test does just the basics to see if it follows or not and does not record anything anywhere. 
# If you want to record, you can mount a new file similar 
# to the one just made to get the resources of the limits. 
# Sorry my english ..... 
# I hope this example will be useful to someone who equals me,
# is starting with this wonderful lib tweepy

**Comment by Harmon758** [comment]
From the following, you can see that the Friendship model just parses the relationship data from Twitter's API:
https://github.com/tweepy/tweepy/blob/cc3c8e7cae73d28b9a75edb7342f89f04da99702/tweepy/models.py#L223-L239 For an example for what that looks like when returned by the friendships/show endpoint, you can see Twitter's API documentation at https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show.html.

What you're interested in is accessible through `friendship[0].following`/`friendship[1].followed_by` or `friendship[1].following`/`friendship[0].followed_by`, depending on which direction the follow is between source and target.
