### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by Thetexassooner1** [tweepy/tweepy#743]
Every time I use import tweepy I get this error:

import tweepy
  File "C:\Python351\lib\site-packages\tweepy__init__.py", line 16, in <module>
    from tweepy.auth import OAuthHandler, AppAuthHandler
  File "C:\Python351\lib\site-packages\tweepy\auth.py", line 9, in <module>
    from requests_oauthlib import OAuth1Session, OAuth1
  File "C:\Python351\lib\site-packages\requests_oauthlib__init__.py", line 1, in <module>
    from .oauth1_auth import OAuth1
  File "C:\Python351\lib\site-packages\requests_oauthlib\oauth1_auth.py", line 6, in <module>
    from oauthlib.common import extract_params
  File "C:\Python351\lib\site-packages\oauthlib\common.py", line 28, in <module>
    import urlparse
  File "C:\Python351\lib\urlparse.py", line 416
    raise ValueError, "bad query field: %r" % (name_value,)
                    ^
SyntaxError: invalid syntax

Process finished with exit code 1

When I'm not using tweepy it works fine. I'm currently am using Python 3.5.1

**Comment by Harmon758** [comment]
[urlparse](https://docs.python.org/2/library/urlparse.html) was renamed to urllib.parse in Python 3.
I'm not sure how you have urlparse.py in your lib directory, but it should not be there in a normal vanilla Python 3.5.1 installation.
OAuthLib, a dependency of Tweepy, expects an import error when trying to import urlparse in Python 3, and handles it by importing urllib.parse as urlprase instead. However, in your case, since it exists, it attempts to import the Python 2 file and results in a syntax error.
This is an issue with your Python installation's standard library rather than an issue with Tweepy.

**Comment by ruchigupta237** [comment]
Thank you for the solution. I had installed python 2 and python 3 both and was getting this error. now after removing the path for python2 in environment variables, it works like a charm. Thanks!
