### ISSUE TITLE
TweepError: failed to send request

### ISSUE THREAD

**Issue by kmario23** [tweepy/tweepy#745]
It was executing perfectly but all of a sudden it started throwing this error, though I did not make any changes to the codebase.

> searched_tweets = ( status._json for status in tweepy.Cursor(api.search, q=query, count=300, since=from_date, until=to_date,
>   File "build/bdist.linux-x86_64/egg/tweepy/cursor.py", line 197, in next
>   File "build/bdist.linux-x86_64/egg/tweepy/cursor.py", line 108, in next
>   File "build/bdist.linux-x86_64/egg/tweepy/binder.py", line 245, in _call
>   File "build/bdist.linux-x86_64/egg/tweepy/binder.py", line 189, in execute
> tweepy.error.TweepError: Failed to send request: 'module' object has no attribute 'HTTPMessage'

Any help is highly appreciated!

**Comment by Aaron1011** [comment]
Can you reproduce this with the latest Tweepy from Github (run `python setup.py install` to replace the installed version from PyPi).

**Comment by Harmon758** [comment]
This seems to have been an issue with the `requests` dependency's `urllib3` dependency having issues when installed along with specific versions of `future` (see https://github.com/elastic/elasticsearch-py/issues/253 and https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=796356) rather than an issue with Tweepy.
However, you seem to have [figured this out already](https://stackoverflow.com/questions/37796502/tweepy-error-attribute-error/37819989#37819989).
