### ISSUE TITLE
HTTPSConnectionPool(host='api.twitter.com', port=443)

### ISSUE THREAD

**Issue by AndyShan** [tweepy/tweepy#756]
Hi,I want to use streaming api to get some tweet,but i have some problem.
It's a simple demo.This is my code:

import tweepy
from tweepy import OAuthHandler

consumer_key = 'YOUR-CONSUMER-KEY'
consumer_secret = 'YOUR-CONSUMER-SECRET'
access_token = 'YOUR-ACCESS-TOKEN'
access_secret = 'YOUR-ACCESS-SECRET'

auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)

api = tweepy.API(auth)

for status in tweepy.Cursor(api.home_timeline).items(10):
    print(status.text) 

and these are error information:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\tweepy\cursor.py", line 197, in next
    self.current_page = self.page_iterator.next()
  File "C:\Python27\lib\site-packages\tweepy\cursor.py", line 108, in next
    data = self.method(max_id=self.max_id, parser=RawParser(), _self.args, *_sel
f.kargs)
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 245, in _call
    return method.execute()
  File "C:\Python27\lib\site-packages\tweepy\binder.py", line 189, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: HTTPSConnectionPool(host='api.t
witter.com', port=443): Max retries exceeded with url: /1.1/statuses/home_timeli
ne.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.Ver
ifiedHTTPSConnection object at 0x0000000002E6DBE0>: Failed to establish a new co
nnection: [Errno 10060] ',))

please help me,thank you.

**Comment by GregoryEady** [comment]
I am receiving the same error. From a thread from another Twitter library, the author writes that the problem is the following:

"This might be caused because the querystring is too long. In Twython 3.1.0 lookup_user was changed from a GET to a POST which will allow a lot more data to be passed to the lookup_user endpoint." (and when the original poster upgraded, this fixed the problem).

**Comment by JazzyDel** [comment]
Hey man, do you find solution to your code?

**Comment by AndyShan** [comment]
This program is developed in China,because of some reason,China is prohibited to visit twitter.
So I use proxy named shadowsockets, it can set mode to global.

**Comment by xiaochenwang94** [comment]
You give the right solution, thank you! @AndyShan

**Comment by SaharNasiri** [comment]
@AndyShan,
I have the same error in my code, and I do not know how to fix it.
I installed VPN and shadowsocks. The VPN is not doing anything apparently for this code, and about the shadowsocks, I do not know what to give inputs for server address, password, remark. Would you help me please?

#Import the necessary methods from tweepy library
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

#Variables that contains the user credentials to access Twitter API
access_token = "ENTER YOUR ACCESS TOKEN"
access_token_secret = "ENTER YOUR ACCESS TOKEN SECRET"
consumer_key = "ENTER YOUR API KEY"
consumer_secret = "ENTER YOUR API SECRET"


#This is a basic listener that just prints received tweets to stdout.
class StdOutListener(StreamListener):

    def on_data(self, data):
        print data
        return True

    def on_error(self, status):
        print status


if __name__ == '__main__':

    #This handles Twitter authetification and the connection to Twitter Streaming API
    l = StdOutListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    stream = Stream(auth, l)

    #This line filter Twitter Streams to capture data by the keywords: 'python', 'javascript', 'ruby'
    stream.filter(track=['python', 'javascript', 'ruby'])

**Comment by duong4996** [comment]
I got the same problem: requests.exceptions.ProxyError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json
?delimited=length (Caused by ProxyError('Cannot connect to proxy.', timeout('timed out',))). 
I run my code in pythonanywhere.com. Can you help me to fix this, pls!

**Comment by xxNB** [comment]
@AndyShan 我使用了shadowsockets并且设置为全局模式，为什么还是出现requests.exceptions.ConnectionError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10bd402b0>: Failed to establish a new connection: [Errno 65] No route to host',))

**Comment by AndyShan** [comment]
@xxNB Our error code is different, I don't know exactly where your problem is. Maybe this can help you, [https://stackoverflow.com/questions/12601316/how-to-make-python-requests-work-via-socks-proxy](https://stackoverflow.com/questions/12601316/how-to-make-python-requests-work-via-socks-proxy)

**Comment by xxNB** [comment]
@AndyShan thanks
Can help me try the following code you can get the data there?

from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream


import json
import pandas as pd
import matplotlib.pyplot as plt
import io


import re

consumer_key = 'qEgHKHnL55g7k4U9xihiCzdVj'
consumer_secret= 'QcUDHJS04wK5hrmlxV5C4gweiRPDca9JQoc4gp7ftHOTgZAdbf'
access_token = '863573499436122112-LA60oJLBzwVnhZjGOUPzRsJcU1wYzs9'
access_token_secret= '8CKFpp6qyxkAk1KfjW7kMRqJPoHKloppPrvd7Tjiwllyk'




#This is a basic listener that just prints received tweets to stdout.
class StdOutListener(StreamListener):

    def on_data(self, data):
        print (data)
        saveFile = open ('kungfu.txt', 'a') # dalailama.twitter1.json cvs
        saveFile.write(data)
        saveFile.write('\n')
        saveFile.close()
        return True

    def on_error(self, status):
        print (status)


if __name__ == '__main__':
    # proxies = {'proxy': 'https:\\111.155.116.233:8123',
    #            }
    #This handles Twitter authetification and the connection to Twitter Streaming API
    l = StdOutListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    stream = Stream(auth, l , )

    #This line filter Twitter Streams to capture data by the keywords: 'python', 'javascript', 'ruby'
    # stream.filter(track=['@dalailama']) # @dalailama
    stream.filter(track=['python']) # @dalailama

**Comment by xxNB** [comment]
@AndyShan 我解决问题了，shadowsockets走的是socket5，我把它改成http走，然后再添加stream的http代理

**Comment by tworitdash** [comment]
I think the Stream class doesn't take the proxy argument. The API class takes both auth and proxy, where as while streaming we only pass the api.auth or simply the authentication (not the proxy). Same goes with the filter method.

If I assign the api like this:

`auth = tweepy.API(auth, proxy='https://your_proxy.server:port`)'

After this all the method calls for auth works (auth.xxx), however, on the Stream class we don't pass the proxy. Therefore, the communication doesn't hold good for other methods. Can anything be done for this?

**Comment by kushalg36** [comment]
I was getting the same error. I was executing tweepy library in kaggle kernel. What i did was I went to the settings in bottom-right corner of the kernel and clicked on internet-connected. Hope this will help.

**Comment by rk173238** [comment]
change your browser proxy or disable it, it will work .

**Comment by Khalid-Usman** [comment]
Currently i am working on this, but unfortunately i am unable to create app at developer.twitter.com to get my API_keys and API_secrets. Can anyone guide me how to answer to successfully create app. 

Thanks

**Comment by Harmon758** [comment]
This traceback is simply an error connecting to Twitter's API.
If you're just unable to connect to Twitter at all, this isn't an issue with Tweepy.
As already pointed out, the Great Firewall of China blocks Twitter, so if you're attempting to connect to Twitter in China, you'll have to use a proxy or other method.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

@xxNB You're going to want to revoke and regenerate your credentials, if you haven't already.

@tworitdash This is a separate issue.
Streams should now support proxies with https://github.com/tweepy/tweepy/commit/2efe385fc69385b57733f747ee62e6be12a1338b (#1033) in Tweepy v3.7.0.

@Khalid-Usman This is a separate issue.
See https://developer.twitter.com/en/docs/basics/getting-started and https://developer.twitter.com/en/docs/basics/apps/overview.

**Comment by yasinaziz** [comment]
l = MyStreamListener()
stream = tweepy.Stream(auth, l, file_name=tweet_file_name, mode=file_mode, max_tweets=100)

# filters twitter streams to capture data by keywords
stream.filter(track=filter_words)



this is the result:
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
~\Anaconda\lib\site-packages\urllib3\connection.py in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 

~\Anaconda\lib\site-packages\urllib3\util\connection.py in create_connection(address, timeout, source_address, socket_options)
     56 
---> 57     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     58         af, socktype, proto, canonname, sa = res

~\Anaconda\lib\socket.py in getaddrinfo(host, port, family, type, proto, flags)
    747     addrlist = []
--> 748     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    749         af, socktype, proto, canonname, sa = res

gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~\Anaconda\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

~\Anaconda\lib\site-packages\urllib3\connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    342         try:
--> 343             self._validate_conn(conn)
    344         except (SocketTimeout, BaseSSLError) as e:

~\Anaconda\lib\site-packages\urllib3\connectionpool.py in _validate_conn(self, conn)
    838         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 839             conn.connect()
    840 

~\Anaconda\lib\site-packages\urllib3\connection.py in connect(self)
    300         # Add certificate verification
--> 301         conn = self._new_conn()
    302         hostname = self.host

~\Anaconda\lib\site-packages\urllib3\connection.py in _new_conn(self)
    167             raise NewConnectionError(
--> 168                 self, "Failed to establish a new connection: %s" % e)
    169 

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x00000091F6284EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~\Anaconda\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

~\Anaconda\lib\site-packages\urllib3\connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    637             retries = retries.increment(method, url, error=e, _pool=self,
--> 638                                         _stacktrace=sys.exc_info()[2])
    639             retries.sleep()

~\Anaconda\lib\site-packages\urllib3\util\retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    398         if new_retry.is_exhausted():
--> 399             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    400 

MaxRetryError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000091F6284EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-15-565877254fe3> in <module>
      3 
      4 # filters twitter streams to capture data by keywords
----> 5 stream.filter(track=filter_words)

~\Anaconda\lib\site-packages\tweepy\streaming.py in filter(self, follow, track, is_async, locations, stall_warnings, languages, encoding, filter_level)
    472             self.body['filter_level'] = filter_level.encode(encoding)
    473         self.session.params = {'delimited': 'length'}
--> 474         self._start(is_async)
    475 
    476     def sitestream(self, follow, stall_warnings=False,

~\Anaconda\lib\site-packages\tweepy\streaming.py in _start(self, is_async)
    387             self._thread.start()
    388         else:
--> 389             self._run()
    390 
    391     def on_closed(self, resp):

~\Anaconda\lib\site-packages\tweepy\streaming.py in _run(self)
    318             # call a handler first so that the exception can be logged.
    319             self.listener.on_exception(exc_info[1])
--> 320             six.reraise(*exc_info)
    321 
    322     def _data(self, data):

~\Anaconda\lib\site-packages\six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

~\Anaconda\lib\site-packages\tweepy\streaming.py in _run(self)
    271                                             auth=auth,
    272                                             verify=self.verify,
--> 273                                             proxies = self.proxies)
    274                 if resp.status_code != 200:
    275                     if self.listener.on_error(resp.status_code) is False:

~\Anaconda\lib\site-packages\requests\sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    531         }
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 
    535         return resp

~\Anaconda\lib\site-packages\requests\sessions.py in send(self, request, **kwargs)
    644 
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 
    648         # Total elapsed time of the request (approximately)

~\Anaconda\lib\site-packages\requests\adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    514                 raise SSLError(e, request=request)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 
    518         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='stream.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/filter.json?delimited=length (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x00000091F6284EF0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by yasinaziz** [comment]
help for this anyone

**Comment by Harmon758** [comment]
Again, this simply indicates you're failling to connect to Twitter's API.
If you're just unable to connect to Twitter at all, this isn't an issue with Tweepy.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by yasinaziz** [comment]
i already connected to twitter but this to filter words

**Comment by itayseer** [comment]
> shadowsockets
How to use it?

**Comment by dheeman00** [comment]
After seeing many comments regarding this error.  The point I got is that when the network is unstable, the API through this error. I get this error when I am trying the follower IDs of users. The crawler does not stop for me as I have put the extraction in the while loop. The problem I am facing is that the extraction starts from the beginning when I encounter this error. But is there any way to handle this error when the follower IDs are extracted?

**Comment by Harmon758** [comment]
See #1606

**Comment by satyamarris** [comment]
> Hi,I want to use streaming api to get some tweet,but i have some problem.
> It's a simple demo.This is my code:
> 
> import tweepy
> from tweepy import OAuthHandler
> 
> consumer_key = 'YOUR-CONSUMER-KEY'
> consumer_secret = 'YOUR-CONSUMER-SECRET'
> access_token = 'YOUR-ACCESS-TOKEN'
> access_secret = 'YOUR-ACCESS-SECRET'
> 
> auth = OAuthHandler(consumer_key, consumer_secret)
> auth.set_access_token(access_token, access_secret)
> 
> api = tweepy.API(auth)
> 
> for status in tweepy.Cursor(api.home_timeline).items(10):
> print(status.text)
> 
> and these are error information:
> 
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Python27\lib\site-packages\tweepy\cursor.py", line 197, in next
> self.current_page = self.page_iterator.next()
> File "C:\Python27\lib\site-packages\tweepy\cursor.py", line 108, in next
> data = self.method(max_id=self.max_id, parser=RawParser(), _self.args, *_sel
> f.kargs)
> File "C:\Python27\lib\site-packages\tweepy\binder.py", line 245, in _call
> return method.execute()
> File "C:\Python27\lib\site-packages\tweepy\binder.py", line 189, in execute
> raise TweepError('Failed to send request: %s' % e)
> tweepy.error.TweepError: Failed to send request: HTTPSConnectionPool(host='api.t
> witter.com', port=443): Max retries exceeded with url: /1.1/statuses/home_timeli
> ne.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.Ver
> ifiedHTTPSConnection object at 0x0000000002E6DBE0>: Failed to establish a new co
> nnection: [Errno 10060] ',))
> 
> please help me,thank you.

I was facing same error. I tried to find out on Internet but I wasn't. So, I tried running that python file through terminal and It worked. Don't Run that File through IDE like (Pycharm). Code the File and Run it through Terminal by Locating the File Directory and Using Command "Python Filename".
