### ISSUE TITLE
malformed string error from examples/streaming.py  'data'

### ISSUE THREAD

**Issue by aspiringguru** [tweepy/tweepy#758]
My first 'issues' post on github, be gentle and redirect if needed.  :)

Working from the streaming example.
https://github.com/tweepy/tweepy/blob/master/examples/streaming.py
my code
https://github.com/aspiringguru/twitterDataAnalyse/blob/master/tweepy_streaming_example.py
my problem:
I'm seeing a badly formed dictionary in string format. 
currently trapping malformed string error from ast.literal_eval(data)

sample output below from 'print(data)' shows malformed string representation of dictionary at keyword 'rel'.

I saw some tools for dealing with malformed json, csv etc, those seem bad solutions.

That said, and given this sample code has been up for a while, I'm wondering how else I should be extracting from data.

{
"created_at":"Fri Jul 15 01:56:59 +0000 2016",
"id":753770301977038848,
"id_str":"753770301977038848",
"text":"I need to start playing basketball more \ud83d\ude10",
"source":"\u003ca href=\"http:\/\/twitter.com\/download\/iphone\" 
rel=\"nofollow\"\u003eTwitter for iPhone\u003c\/a\u003e",
"truncated":false,
"in_reply_to_status_id":null,
"in_reply_to_status_id_str":null,
"in_reply_to_user_id":null,

etc...

**Comment by lewisjb** [comment]
Have you tried `json.loads(data)`?

**Comment by aspiringguru** [comment]
Thanks Lewisjb.

That works. Thanks. Not sure why I didn't think of that. 

data was showing as type unicode. but yeah... it looks like json, I should have recognised json.

The json data kind of negates my next question and raises Q2.

Q1.
on another note: I'm struggling with the creation of methods under tweepy.StreamListener.
ie: can I create two methods as below and have them run with each new tweet received? (apparently not - so I feel like I don't understand this program structure properly)

def on_id(self, id)
on_location(self, location)
example code.
https://github.com/aspiringguru/twitterDataAnalyse/blob/master/tweepy_streaming_example_2.py

q2: 
I'm wondering how to maximise efficient use of the filter request-parameters and test conditions within the on_data method. 
https://dev.twitter.com/streaming/overview/request-parameters
stream.filter(track=['basketball'], async=True)

One of the documention notes mentioned handing the data to another process, database or writing to file to enable keeping up with the stream.  [which also raises the question 'can I restrict the stream bandwidth, and 'is there a rate limit' for streams. ]

**Comment by lewisjb** [comment]
Not sure how much help I'll be but I'll give it a shot.

1. Looking at https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L30 might give you a better idea of how it works. You can totally create new methods and call multiple of them, it's just extracting the data that is the problem. And since you are overriding `on_data` the default functions won't be called, so if you also want them then I would recommend copying the original `on_data` and just extending it.

2. Not sure how you can maximize efficient use; it might be beneficial to start out really broad, and then from analyzing the data you can most likely start to hone in on the right filters.

2a. I don't believe there is a specific way to limit the amount on your end except setting tighter filters.
2b. https://dev.twitter.com/tags/streaming-api yes there is
