### ISSUE TITLE
Issue with User_timeline()

### ISSUE THREAD

**Issue by Camofelix** [tweepy/tweepy#763]
having an issue where calling user time line is returning `IndexError: list index out of range` with the initial call string being
 `
for status in api.user_timeline([309626491][743090778923098112][False][1][1]):
    print status.id
    tweet= status.id
    api.retweet(tweet)
    time.sleep(900)
`

In terms of debugging I've tried the old indexing from 0 attempt and playing around with the start and end point but cant seem to get this to function 

I've read the specific documentation on http://docs.tweepy.org/en/v3.5.0/api.html#API.user_timeline

**Comment by zhangoose** [comment]
@camofelix Hey, I could be wrong, but I think that the documentation is a little unclear about how you're supposed to be calling the API. The `[]`s actually mean that those parameters are optional. 

If you do:

```
user_timeline = api.user_timeline()
print(user_timeline)
```

You get back the user timeline for the account whose access token & secret you used to set up the API (basically `auth` in http://tweepy.readthedocs.io/en/v3.5.0/getting_started.html#introduction)

But if you do:

```
user_timeline = api.user_timeline("309626491")
print(user_timeline)
```

You get back the user timeline for the twitter account ID `309626491`.

**Comment by Harmon758** [comment]
This is because with `[309626491][743090778923098112]`, you're defining a list with a single integer,  `309626491`, and attempting to access that list with the index, `743090778923098112`.
In terms of documentation, items enclosed in brackets are optional.
This is an established variant feature of [Backus–Naur form](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_form) that is [standard to Python](https://docs.python.org/3/reference/introduction.html#notation).
