### ISSUE TITLE
Twitter new changes: Request to implement tweet_mode=extended

### ISSUE THREAD

**Issue by amir-psi** [tweepy/tweepy#785]
Hello everybody

As you may know already, Twitter made some changes which affected its API:
https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

Now, if I get the JSON file for this tweet:
https://twitter.com/i/web/status/777915304261193728

I will get only this
"Say more about what's happening! Rolling out now: photos, videos, GIFs, polls, and Quote Tweets no longer count tow… https://t.co/SRmsuks2ru3".

Which means there are some letters missing from tweepy current output. It seems there is a solution for it mentioned in the first link above, but I couldn't get the tweet_mode=extended into an API request.

Now, I was wondering if the tweet_mode=extended will be implemented in tweepy or someone has a brilliant idea how to get the rest of that tweet: ''ard your 140 characters.'' ?

Cheers

**Comment by arijeetmkh** [comment]
From what I can see, `tweet_mode=extended` can be easily sent via extra kwargs to most of the method calls. The only exception is the `statuses_lookup` method where extra kwargs are strictly limited to a few of them. Sending `tweet_mode=extended` would require changing the signature of the `tweepy.api.API.statuses_lookup` method, since for some reason, this particular method is not implemented directly as a property.

**Comment by MichaelMallett** [comment]
@arijeetmkh how can these be sent easily via kwargs?

**Comment by 11LindseyBass11** [comment]
Hello guys,

I am trying to download tweets using tweepy with tweet_mode=extended and my query looks like this:

tweepy.Cursor(api.search,q='to%3ANASA&tweet_mode=extended').items(limit)

, but I keep getting zero results. As soon as I remove the &tweet_mode=extended part from the query, I get plenty of results:

tweepy.Cursor(api.search,q='to%3ANASA').items(limit)

Is it still the right way to form a query? Any idea why am I not getting anything with extended mode?  Hope you can help!

Thanks so much,
Lindsey

**Comment by arijeetmkh** [comment]
The keyword argument for `extended_mode` needs to be added to the service call (in this case search service). In you case, since you are using a cursor, the keyword argument will be a part of the `tweepy.Cursor` constructor.

ie,
`tweepy.Cursor(api.search, q='to:3NASA', tweet_mode='extended').items(limit)`

This should give you a result where each tweet contains a property called `full_text` instead of the usual `text`.

**Comment by 11LindseyBass11** [comment]
Thanks for such a prompt answer! It's working now!

**Comment by eholobyn24** [comment]
Using the following code snip but getting an error:

Code Snip:
for tweet in tweepy.Cursor(api.search,q=q,rpp=100,result_type='recent',include_entities=True,lang='en',tweet_mode= 'extended').items(i):

Error:
AttributeError: 'Status' object has no attribute 'text'
