### ISSUE TITLE
stream.filter just hangs

### ISSUE THREAD

**Issue by 4score** [tweepy/tweepy#788]
Hi guys,

What would cause the filter method to just hang? no matter the arguments it doesn't do anything. On the other hand, the stream.sample method immediately starts outputting data

my call to filter looks like this:
`stream.filter( locations=[-124, 48, -65, 24], languages=['en'] )`

I have to use ctrl-c to kill the process and then this is output to terminal:
`^CTraceback (most recent call last):
  File "main.py", line 89, in <module>
    stream.filter( locations=[-125, 50, -65, 24], languages=['en'] )
  File "/usr/lib/python3.4/site-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/lib/python3.4/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/lib/python3.4/site-packages/tweepy/streaming.py", line 255, in _run
    sleep(self.retry_time)
KeyboardInterrupt
`

Tthanks for any help

**Comment by Aaron1011** [comment]
@4score: Are you sure that tweets are being posted from those locations? I would use the `track` parameter to ensure that the issue isn't on your end.

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Instead, I get a 406 Not Acceptable response, likely because:
> Each bounding box should be specified as a pair of longitude and latitude pairs, with the southwest corner of the bounding box coming first.

and your specified bounding box has the northwest corner first instead.

See https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
