### ISSUE TITLE
"No Longer Maintained" Why? 

### ISSUE THREAD

**Issue by lababidi** [tweepy/tweepy#803]
This seems as a surprise as this project is incredibly popular and depended upon by many people and organizations. Could the people who made this decision explain the basis of this decision?

**Comment by fitnr** [comment]
see #792 for more on this topic

**Comment by uogbuji** [comment]
I wondered the same thing, and I found [this explanation from the maintainer(https://groups.google.com/forum/#!topic/tweepy/rWOKWGzdTVE). Later i nthe thread he says:

"I am open to transferring ownership of the project if someone is willing to come forward and maintain it. If you have the passion and time to manage pull requests, releases, etc then I think you would be a good fit."

So that's fair enough and one hopes someone can step up.

**Comment by fitnr** [comment]
@uogbuji that conversation is from 2013.

**Comment by uogbuji** [comment]
@fitnr true, I assumed that was the lead-in to your comment above re #792, but I guess not, with a three year lag ;) Glad a handover finally seems to be getting traction.

**Comment by kodeine** [comment]
can someone fork it and start updates on that? since the owner of this repo doesnt care anymore :)

**Comment by haraldschilly** [comment]
@kodeine better would be to transfer the ownership, or be part of this github group and so on, since otherwise the issues and PRs are either lost or it's much more work.

**Comment by Aaron1011** [comment]
As I said [here](https://github.com/tweepy/tweepy/issues/792#issuecomment-255227324), I'm going to be taking over the project - either today or this weekend, I'll be reviewing all of the open PRs and issues.
