### ISSUE TITLE
TweepError

### ISSUE THREAD

**Issue by luoling1993** [tweepy/tweepy#813]
hello:
       i want to catch error code but get some error.

code:
try:
     do something
except tweepy.TweepError as err:
     print(err)

output:
[{'code': 88, 'message': 'Rate limit exceeded'}]

i want to get 88, so i use err[0]['code']  but error
or try to err.reason[0]['code'] bur TypeError: string indices must be integers

**Comment by unabomber87** [comment]
hello 
err is a TweepError object which has 3 attributes (reason, response and api_code)
reason contain the str [{'code': 88, 'message': 'Rate limit exceeded'}] 
so you must convert it to json or something similar to get the error code

```
try:
	do something 
except tweepy.RateLimitError as err:
	tojson = json.loads(err.reason.replace("[", "").replace("]", "").replace("'", "\""))
	print(tojson["code"])
```

**Comment by fitnr** [comment]
This is convoluted advice, although the code shows the better way to handle this. Catch `RateLimitError`s separately and handle them - there's really no need to get the response code.

````python
try:
    do_something()

except tweepy.RateLimitError as err:
    # err.api_code isn't assigned here, which is perhaps a little silly but you don't need it!
    print(88)

except tweepy.TweepError as err:
    print(err.api_code)
````

**Comment by Aiiiiii** [comment]
I met the same problem. Any update?

**Comment by Harmon758** [comment]
As @​fitnr outlined, you can simply use [`RateLimitError`](https://tweepy.readthedocs.io/en/latest/api.html#RateLimitError) instead.
Otherwise, you can simply use the `TweepError.api_code` attribute:
https://github.com/tweepy/tweepy/blob/a8e85263bd20e95322a874344a4776f2b9e7726c/tweepy/error.py#L8-L18  and check for 88.

> so i use err[0]['code'] but error

`err` is a `TweepError` object/exception, so indexing it by 0 makes no sense, which is why an error is raised if you attempt to do so.
> or try to err.reason[0]['code'] bur TypeError: string indices must be integers

`TweepError.response` is the payload response Twitter's API is returning as a string.
In this case, it would be `"[{'code': 88, 'message': 'Rate limit exceeded'}]"` as you see in the string representation of the `TweepError`.
You access the string via index 0, retrieving the first character, `'['`, and then you attempt to index that character by `'code'`, hence resulting in the `TypeError` telling you that you can't access a string/character with a string index.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
