### ISSUE TITLE
Does tweepy support control stream for site stream?

### ISSUE THREAD

**Issue by jonathansp** [tweepy/tweepy#823]
Does tweepy support [control stream for site stream](https://dev.twitter.com/streaming/sitestreams/controlstreams)? Is it in your roadmap?

**Comment by Aaron1011** [comment]
@jonathansp: I had been thinking about adding support, but twitter is apparently [no longer accepting applications for access](https://dev.twitter.com/streaming/sitestreams). As such, I would have no idea the implementation would even work.

**Comment by jonathansp** [comment]
@Aaron1011: Even though there has been some work to do, It seems straightforward to implement control stream. If I had I already authorized token, I would be able to work on that.

**Comment by Harmon758** [comment]
This is now stale since Site Streams have been deprecated and retired.

See:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
