### ISSUE TITLE
Way too many outside libraries used

### ISSUE THREAD

**Issue by Peteous** [tweepy/tweepy#841]
When you install the tweepy library, so discover that tweepy uses 4 other libraries that it doesn't package in. You end up spending 4 hours adding in those libraries and trying to troubleshoot why they won't run. It makes this library completely useless.

**Comment by Harmon758** [comment]
Four dependencies is hardly "way too many". Even requests, one of the most popular Python libraries (and one that Tweepy itself actually uses), has four dependencies.

I'm not sure what you mean by "doesn't package in." The required dependencies are documented through requirements.txt and setup.py, as is standard. Python libraries aren't "packaged" together with their dependencies. You simply install them along with their dependencies.

> You end up spending 4 hours adding in those libraries and trying to troubleshoot why they won't run.
> It makes this library completely useless.

Pip should handle installation of all dependencies. If you're manually installing them, then you're doing something wrong. Without further information, it's impossible to determine what your issue is, but even if you were to install them separately (e.g. if you installed Tweepy with the `--no-dependencies` option), it would simply be four more pip commands. Even so, your failure to install the library is hardly indicative of the usefulness of the library.
