### ISSUE TITLE
Deprecated six library being called?

### ISSUE THREAD

**Issue by Peteous** [tweepy/tweepy#842]
When pip installing tweepy, the process errors out at installing six saying: `Found existing installation six 1.4.1
 DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
`
After this error, tweepy cannot pip install

**Comment by Harmon758** [comment]
Six is hardly deprecated. In fact, as of right now, it's still the second most downloaded library on PyPI.

As that says, it is a deprecation warning, not the actual error/traceback. It's impossible to determine what your issue is without the full traceback.

Even so, this is an issue with pip and/or six, not Tweepy, and a quick search for the deprecation warning returns results (e.g. https://github.com/pypa/pip/issues/3165) that show you're likely encountering a common and easy to mitigate issue.
