### ISSUE TITLE
Don't include all the character of a Tweet 

### ISSUE THREAD

**Issue by yelkamel** [tweepy/tweepy#853]
Hello,

I don't understand why in some tweet, I don't get the full tweet.
I got "…" in the end of the text field of a tweet.

Someone can help me ? 

Thanks

**Comment by mattcanavan** [comment]
what have you tried? (what does your code look like?)

**Comment by yelkamel** [comment]
`def get_all_tweets(screen_name):
    #Twitter only allows access to a users most recent 3240 tweets with this method

    #authorize twitter, initialize tweepy
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api = tweepy.API(auth)

    #initialize a list to hold all the tweepy Tweets
    alltweets = []

    #make initial request for most recent tweets (200 is the maximum allowed count)
    new_tweets = api.user_timeline(screen_name = screen_name,count=200)

    #save most recent tweets
    alltweets.extend(new_tweets)

    #save the id of the oldest tweet less one
    oldest = alltweets[-1].id - 1

    #keep grabbing tweets until there are no tweets left to grab
    while len(new_tweets) > 0:
        print "getting tweets before %s" % (oldest)

        #all subsiquent requests use the max_id param to prevent duplicates
        new_tweets = api.user_timeline(screen_name = screen_name,count=200,max_id=oldest)

        #save most recent tweets
        alltweets.extend(new_tweets)

        #update the id of the oldest tweet less one
        oldest = alltweets[-1].id - 1

        print "...%s tweets downloaded so far" % (len(alltweets))

    #transform the tweepy tweets into a 2D array that will populate the csv
    outtweets = [[tweet.id_str, tweet.created_at, tweet.text.encode("utf-8"),tweet.retweet_count,tweet.favorite_count] for tweet in alltweets]

    #write the csv
    with open('%s_tweets.csv' % screen_name, 'wb') as f:
        writer = csv.writer(f)
        writer.writerow(["id","created_at","text","retweet_count","favorite_count"])
        writer.writerows(outtweets)

    pass`

it's the classic way I guess ?

**Comment by Floricar** [comment]
Hello, I got the same issue some time ago. This is because you are fetching a retweet and thus the text (tweet.text.encode("utf-8")) goes like this: "RT @somescreenname" + "original tweet". 
Since each tweet only goes from 0 to 140 characters, what Twitter does is to truncate the original tweet (and add the "...") to get in the max number of character in the text I just explained. 
You should get the retweeted_status.text attribute of the json response in order to get the complete tweet.

This is a Twitter bug, not a tweepy one.

Hope I get myself explained.
