### ISSUE TITLE
401 respone , from twitter api stream , using python 

### ISSUE THREAD

**Issue by abdolrhman** [tweepy/tweepy#861]
hey guys please help me , suddenly when am using my code to retrieve streaming tweets , using python and of course tweepy , 
i got gust 401 , 
every thing was working fine in windows 7 , but i installed a Linux dis , with all the necessary tools , and when ever i try to run the code i got this error , please can some one help me 

> note : i tried to change the  4keys , still same problem , my data and time are up to date , i used the code in both python 2 and 3 still 

thanks guys in advance

**Comment by Nasr-Z1** [comment]
am using linux , so i know that there is some thing wrong with my services , can i know which services do i need to access and stream tweets in twitter ? 
plllllllease help me here , any thing is great

**Comment by Harmon758** [comment]
I'm unable to reproduce this, and this is likely just the response from Twitter rather than an issue with Tweepy. Can you provide a MCVE/SSCCE?

The description of a 401 error code from the API documentation:
> HTTP authentication failed due to either:
> - Invalid basic auth credentials, or an invalid OAuth request.
> - Out-of-sync timestamp in your OAuth request (the response body will indicate this).
> - Too many incorrect passwords entered or other login rate limiting.

For more information, see https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/connecting and https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request.

Double check that your credentials are valid and that your system clock is in sync with NTP.
