### ISSUE TITLE
401 Unauthorized when streaming

### ISSUE THREAD

**Issue by theandrewchan** [tweepy/tweepy#877]
I'm getting a 401 error, but only when using the `StreamListener`. Normal API calls work fine.

My Twitter account is set to the same timezone as my dev machine, and I still get 401 errors when I run my code on Heroku's servers. What gives? Is Tweepy still hitting v1 API endpoints?

**Comment by berkay-dincer** [comment]
I am having the same issue and troubleshooting for 2 days now. As you mentioned timezone is not the issue, and i've tried it with keys proven to work.

**Comment by aayushiku** [comment]
Same issue here. Unable to figure out.

**Comment by berkay-dincer** [comment]
I was able to figure out the issue after days of debugging. Turns out this is related with the way I read the keys from the property file. Somehow python inserted a subtle ' character to the beginning and end of the keys. 

What lead me to the wrong direction is that this was not immediately obvious for some reason (caching mechanism?) on Twitter side.

**Comment by aayushiku** [comment]
Doesn't seem to be the case with me. Since Auth Handler object is getting instantiated. In my case too, normal api calls work fine. But Streaming doesnt.

**Comment by aayushiku** [comment]
I did manage to figure out the issue. Mine was indeed a timezone issue. I had change the timezone on my ubuntu machine but didnt sync ntp. Once I did that, everything started working fine. Thanks for your help though :) @theandrewchan If your issue is still unresolved, you might wanna give a try at this.

**Comment by bchase77** [comment]
I had the same issue with an IOT device. Somehow the time-of-day on that system got offset by about 2h20min. When I set it back to the correct time (actually sync'd to ntp pool) it started to tweet again.

**Comment by neuhaus** [comment]
Same here, the time was off by 5 minutes and i got 401 errors.

**Comment by manoadamro** [comment]
been trying on and off for about a year... never once had it working

**Comment by iddqd1** [comment]
still the same

**Comment by theandrewchan** [comment]
I switched to [python-twitter](https://github.com/bear/python-twitter), you may want to try that instead.

**Comment by Harmon758** [comment]
I'm unable to reproduce this, and this is likely just the response from Twitter rather than an issue with Tweepy. Can you provide a MCVE/SSCCE?

The description of a 401 error code from the API documentation:
> HTTP authentication failed due to either:
> - Invalid basic auth credentials, or an invalid OAuth request.
> - Out-of-sync timestamp in your OAuth request (the response body will indicate this).
> - Too many incorrect passwords entered or other login rate limiting.

For more information, see https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/connecting and https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request.

Double check that your credentials are valid and that your system clock is in sync with NTP.

**Comment by ruemee** [comment]
Hie, am also facing the same issue , i tried it on another machine and it worked but on my machine it its not working

**Comment by rishi-wqd190004** [comment]
I faced similar issue,my solution to get the output was:
a. check ntp- with system clocked using timedatectl and verify the timesyncd and system clock is synced
b. check the key format you entering
c. if using a third file do check it consist in the same file...common but i made that issue

check this is have issue with timedatectl:https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-18-04

**Comment by seeess1** [comment]
Anybody else getting this same error again? Currently running a tweet-streaming Python script on a GCP VM and getting 401s. 

Batch, non-streaming API calls work fine. So auth is fine. And the script works when I run it from my local machine. So at this point my best guess is that it's a timing issue related to the VM. Does that sound plausible?
