### ISSUE TITLE
Issue with filtering the date of tweets

### ISSUE THREAD

**Issue by farnazkgn** [tweepy/tweepy#887]
Hi,
I am trying to extract the data from Twitter within a range of date and just for a certain city (with no keywords, I want to extract all the Tweets). My code is as below and it is working without date filter but when I add the since="2017-02-01", until="2017-02-27", the output is blank. Can anybody help me to fix it?

import tweepy
import csv

consumer_key = "Doy0JVXbQCXQpHWo7c7Iyi2qa"
consumer_secret = "weC5gr6Ug7BiE57nzn7A0KHnBfQrtdnuENgvxqksNxpEt1o8Gt"
access_token = "272931846-ZcXJl9ynbua6Y4Zygogsdyk2tIKvVZmM3vWsQDL4"
access_token_secret = "HB3k5zs71w6KLVSOhXRIEF8UPcV4eLUJiJv06abB8ssOx"

auth = tweepy.auth.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

# Open/Create a file to append data
csvFile = open('tweets.csv', 'a')
#Use csv Writer
csvWriter = csv.writer(csvFile)

for tweet in tweepy.Cursor(api.search,q="*",geocode="37.2296,80.4139,150km").items(10000):
    print ([tweet.created_at, tweet.text.encode('utf-8'), tweet.geo])

**Comment by Harmon758** [comment]
First of all, you're going to want to revoke and regenerate your keys and tokens if you haven't already.

`since` is not a valid kwarg parameter for [`API.search`](https://tweepy.readthedocs.io/en/latest/api.html#API.search).
See also https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html.

Per the [documentation of Twitter's search endpoint](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators):
> The Search API is not a complete index of all Tweets, but instead an index of recent Tweets. The index includes between 6-9 days of Tweets.

and [of the `until` parameter](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html):

> Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.

This was the reason your search was returning no results, as 2017-02-27 was more than 7-9 days ago from when you made this issue.
To search Tweets older than that limit, you'll have to use the [premium search APIs](https://developer.twitter.com/en/docs/tweets/search/overview/premium).

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
