### ISSUE TITLE
Emoji encoding on streaming API

### ISSUE THREAD

**Issue by afcruzs** [tweepy/tweepy#891]
Hi, I am using a very simple example of the streaming API, but it is failing on the encoding of a tweet with emojis.  My code is roughly the following:

```
class Listener(StreamListener):

    def on_data(self, data):
        self.buffer.append(data)
        print("hello", len(self.buffer))
        print(json.loads(data))

l = Listener()
auth = OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

stream = Stream(auth, l)
stream.filter(follow = [user_id],
              stall_warnings = True,
              encoding = 'unicode-escape')
```
It produces this error

 ` File "streaming.py", line 29, in on_data                                                                                  print(json.loads(data))                                                                                               File "C:\Users\Felipe\Anaconda2\envs\py35\lib\encodings\cp850.py", line 19, in encode                                     return codecs.charmap_encode(input,self.errors,encoding_map)[0]                                                     UnicodeEncodeError: 'charmap' codec can't encode characters in position 2228-2231: character maps to <undefined> `

I have tried various encodings including the by default utf-8 but the method still fails. Is there any way to  enconde emjois properly?.

**Comment by nuvious** [comment]
Getting the same error myself:
`Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 294, in _run
    raise exception
UnicodeEncodeError: 'ascii' codec can't encode character u'\U0001f339' in position 134: ordinal not in range(128)
`

Any time an emoji is in a tweet it breaks the stream and quits out. Is it possible to allow the loop to continue on a UnicodeEncodeError and log the error as a warning? It's frustrating not being able to run the stream continuously with fingers crossed that no one will tweet an emoji. I'm working on a project which requires 7-days of continuous data.

**Comment by Satyam-Bhalla** [comment]
You are getting this error because the python shell and cmd can't encode emojis so if you try to print out a emoji it will not print that and you will get this error. I was also suffering from the same situation but I just found the solution. **Try to implement this in a Jupyter notebook it will work fine**. Just follow these commands...
`pip3 install --upgrade
pip3 install jupyter`
After installing jupyter go to the cmd and type
`jupyter notebook`
It will open the web browser there you can create a new notebook and in that notebook place all the code above and run the kernel. You will not get any error.
More about [Jupyter](http://jupyter.readthedocs.io/en/latest/index.html)

**Comment by tvoitik** [comment]
Has anyone found a solution for this?  It's 2018, nearly every tweet will have an emoji.

**Comment by yiannis-had** [comment]
try:
     # your code
except UnicodeEncodeError:
     pass

**Comment by Harmon758** [comment]
This is an issue with your console's code page/encoding rather than an issue with Tweepy.
You're attempting to print a character outside the range that [CP 850](https://en.wikipedia.org/wiki/Code_page_850) supports.
This is easily resolved by changing the active code page to UTF-8 using [`chcp`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chcp) and specifying [`65001`](https://docs.microsoft.com/en-us/windows/desktop/Intl/code-page-identifiers).

@nuvious This is an unrelated issue that should now be fixed with https://github.com/tweepy/tweepy/commit/0279a4e911db0bf54268366a0cb6ae65ad5f8988 (#606) as part of Tweepy v3.4.0. See #549.
