### ISSUE TITLE
TabError in tweepy.modules

### ISSUE THREAD

**Issue by sedemmler** [tweepy/tweepy#894]
`line 302
    setattr(result, 'is_followed_by', 'followed_by' in v)
                                                        ^
TabError: inconsistent use of tabs and spaces in indentation`

I've looked through tweepy.modules in PyCharm and Anaconda, and notebook++, I cannot find what it's talking about.

Any ideas?

**Comment by fitnr** [comment]
Don't appear to be any tabs in the file.

**Comment by williamhpayne** [comment]
There appears to be a tab on line 301: fixing raises a second error - importerror 'can't load a json library' in utils.py

**Comment by williamhpayne** [comment]
There's a host of issues with tweepy if attempting to use it with Python 3.5. In particular it calls for htmlentitydefs. Best to use it with Python 2.7 I suspect

**Comment by sedemmler** [comment]
I don't see the tabs in my IDE, but, I get the same error regardless. 

Off to 2.7, I go. Thanks guys.

**Comment by Harmon758** [comment]
This error in models.py was fixed with https://github.com/tweepy/tweepy/commit/df4044c922fe294318a803aeb77c79c7f250a986 and released with Tweepy 2.1, almost six years ago (almost four years before this issue was opened).

@williamhpayne I've experienced no issues specific to Python 3.5, 3.6, or 3.7 using Tweepy 3.7.0.
The only issue with Tweepy v3.5.0 and v3.6.0 that was specific to Python 3.7 (async becoming a reserved keyword) was also fixed with Tweepy 3.7.0.
As for your specific example, the only instance of htmlentitydefs being imported was removed with https://github.com/tweepy/tweepy/commit/9b82cfaf242e819de295929332091bd1a2807c42 and released with Tweepy 2.3 more than five years ago (more than three years before this issue and your comment).

Please make sure you're using the latest development version (or at least the latest release) when opening issues and providing advice.
