### ISSUE TITLE
Streaming: disconnect on keep_alive()

### ISSUE THREAD

**Issue by luafran** [tweepy/tweepy#897]
Hi

I have a use case where I want to connect to the streaming API for a period of time and then disconnect even when no tweet is received during that period.

When no tweet is received, I can check if defined duration has elapsed in StreamListener keep_alive(), but there is no mechanism to disconnect in this case since _read_loop() is not reading any return value from keep_alive() and there is no way to break the loop in this situation.

As a workaround I am rising a custom exception in my implementation of keep_alive() but this is not ideal, I understand that a better solution is to let keep_alive() return a boolean that when is false breaks the read loop, same as on_data(), on_status(), etc.

**Comment by anshudwibhashi** [comment]
I support this. I'd too rather have the keep_alive() function return a boolean to determine whether or not the connection continues to exist. Currently, my workaround is to raise an exception in the keep_alive function, and override the on_exception function to return false.

**Comment by aalberti333** [comment]
I would also like to see this implemented.

**Comment by Harmon758** [comment]
This should be resolved with https://github.com/tweepy/tweepy/commit/37e701e2193dcf617e7235d3b004f790c5ff784e by allowing `Stream.disconnect` to disconnect the stream on the next keep-alive signal received.

I opted not to use the approach of allowing a `False` return value from the stream listener's `on_keep_alive` method to indicate that the stream should disconnect, as I intend to remove this for other stream listener methods in Tweepy v4.0 because it's an unclear functionality that should be considered an anti-pattern / bad practice. When necessary, explicitly calling the `Stream.disconnect` method in the relevant stream listener method is clearer and more straightforward.

I also intend to merge `StreamListener` into `Stream` in Tweepy v4.0, which will make doing this simpler and less recursive, i.e. using `self.disconnect` in the relevant listener method rather than requiring the `Stream` instance to be available in the relevant stream listener method.

Afterwards, I anticipate being able to simplify the handling of each line of data, so as to allow the stream to disconnect immediately if `Stream.disconenct` is called in the `on_keep_alive` method, rather than waiting until the next keep-alive signal (or other line of data).

**Comment by Harmon758** [comment]
> I intend to remove this for other stream listener methods in Tweepy v4.0

This is now done, with https://github.com/tweepy/tweepy/commit/7fc85f63c1a322439edf667866c94a29fd7b2199, https://github.com/tweepy/tweepy/commit/7756fa84bc97d0dc3c6c54ed75bc27c9297083ad, and https://github.com/tweepy/tweepy/commit/e348c36f435470985026ae7b93de115db1261041.

> I also intend to merge `StreamListener` into `Stream` in Tweepy v4.0

This is now done with https://github.com/tweepy/tweepy/commit/39abff4520e291180425ac2219d1d8597ac5da96.

> Afterwards, I anticipate being able to simplify the handling of each line of data, so as to allow the stream to disconnect immediately if `Stream.disconenct` is called in the `on_keep_alive` method, rather than waiting until the next keep-alive signal (or other line of data).

This was also done with https://github.com/tweepy/tweepy/commit/7756fa84bc97d0dc3c6c54ed75bc27c9297083ad.
