### ISSUE TITLE
Tweepy - userstream method to monitor my own timeline not working any more

### ISSUE THREAD

**Issue by ghost** [tweepy/tweepy#917]
Hi,

I would be very nice if somebody could help me with the following problem: 

Already some time ago I wrote an application which relies on streaming my own timeline via tweepy into a `neo4j` database. I used the  `stream.userstream(_with='followings)` and until some days ago everything worked perfectly. Now suddenly it doesn't yield any data anymore. The stream just stays silent. No error messages, just nothing. The `stream.filter()` however still works without problem, so it should neither depend on my internet connection nor on any rate limits. What could be the problem?

The only theory I have is, that the 2700 users I follow might be a bit too much. This is the only change I made I can think of: I added approximately 100 users in the last couple of days.

Edit: I forgot to write: I am using Python 3 (3.5 before, now I updated to Python 3.62 as I read online that this problem might have to do with the Python version). If I leave away `_with='followings`it seems to work, but not as before. I am not getting all the tweets in my timeline.

**Comment by ma-ga-re** [comment]
I too had the same problem. In my case only one function out of "stream.filter()" and "stream.userstream()" run at a time.

**Comment by Harmon758** [comment]
This issue is now stale, since User Streams have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
