### ISSUE TITLE
Can anyone confirm the languages parameter only works on the filter stream?

### ISSUE THREAD

**Issue by ClaasM** [tweepy/tweepy#918]
In the Streaming request parameter [documentation](https://dev.twitter.com/streaming/overview/request-parameters#filter_level) it says that

> This parameter may be used on all streaming endpoints, unless explicitly noted.

for the `languages` and the `locations` parameter.

However, tweepy only uses it on the filter stream, because thats the only endpoint where these two parameters are explicitly documented again in the [endpoint documentation](https://dev.twitter.com/streaming/reference/post/statuses/filter).

Before I do any testing myself: Can anyone confirm that the `languages` and `locations` parameters have no effect on i.e. the user stream?

**Comment by Harmon758** [comment]
This issue is now stale, since User streams have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
