### ISSUE TITLE
Doc to Tweepy?

### ISSUE THREAD

**Issue by victorpenna** [tweepy/tweepy#927]
Is the tweepy documentation incomplete? In some surveys, having problems with tweepy, I found solutions in forums with other methods and functions used for research that are not included in the documentation. For example, additional search parameters .. query = "word1 OR word2", etc.

**Comment by richyvk** [comment]
I have the same question. I'm going to say it is incomplete. For example the docs only mention a few of the available API methods. I spent ages earlier trying to figure out how to get mentions, only to discover there is a mentions_timeline method.

Is this intentional, is there some logic to what gets into the docs? Or can people contribute more to the docs to get them more complete?

**Comment by victorpenna** [comment]
I found my answer, as far as read documentation on Twitter. However I believe it was a mistake of the developers as to the information. They should put a note .... "For more functionality, look up the native functions of the Twitter API".
Although I already completed my part, I needed a lot of time to do it, mainly reading the twitter API features and forums like stackoverflow.
Follow the twitter API documentation link:
https://developer.twitter.com/en/docs/basics/getting-started
