### ISSUE TITLE
Not Work Tweepy on Python

### ISSUE THREAD

**Issue by flukedf** [tweepy/tweepy#936]
Yesterday I worked in python it was good, but today not working I don't what happened

**Comment by fitnr** [comment]
Did you try turning Twitter off and then on again? 😄 

When my code suddenly stops working, it's usually because I was totally wrong about a small change that I was sure wouldn't change anything.

If you think you're running into a bug in Tweepy, please add more detail with your code, what happened, what you thought should happen, and any error messages.

If you think you need help understanding the Twitter API or the Tweepy code, a forum like StackExchange might be a better place to go for help.

**Comment by Harmon758** [comment]
This is extremely vague and provides absolutely no information about what your issue is.
You'll need to explain your issue for it to be actionable.
