### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by Nicolealexandra58** [tweepy/tweepy#956]
When I use the following to download tweepy:

git clone https://github.com/tweepy/tweepy.git
cd tweepy
python setup.py install

I get the following error message after entering "python setup.py install":

Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from pip.req import parse_requirements
ImportError: No module named pip.req

What should I do to complete the install?

**Comment by fitnr** [comment]
Install [pip](https://pip.pypa.io/en/stable/installing/), which is a Python package manager.

**Comment by Harmon758** [comment]
This is due to [a change](https://github.com/pypa/pip/commit/95bcf8c5f6394298035a7332c441868f3b0169f4#diff-851cc85103a872db421c81afadd4fee5) (https://github.com/pypa/pip/pull/4700) in pip 10.0.0 (see #1029) and should be fixed by https://github.com/tweepy/tweepy/commit/29e32cdf4a67b1fca25dbf04d7b8069ac1c9dd0d (#1030) in [3.7.0](https://github.com/tweepy/tweepy/releases/tag/3.7.0).
