### ISSUE TITLE
report_spam returns error code 34 

### ISSUE THREAD

**Issue by CharlotteCross1998** [tweepy/tweepy#960]
api.report_spam("twitter") returns
`Error reporting: [{'code': 34, 'message': 'Sorry, that page does not exist'}]
`

I have tried the following:

```
api.report_spam("twitter")
api.report_spam("@twitter")
api.report_spam(id="twitter")
api.report_spam(id="@twitter")
```

**Comment by Jebbss** [comment]
is it possible your passing the wrong parameter to it? 

from tweepy/api.rst 
.. method:: API.report_spam([id/user_id/screen_name])

   The user specified in the id is blocked by the authenticated user and
   reported as a spammer.

   :param id: |uid|
   :param screen_name: |screen_name|
   :param user_id: |user_id|
   :rtype: :class:`User` object

**Comment by biggydbs** [comment]
I can work on it.

**Comment by bpb27** [comment]
any update on this? i've been using the user_timeline method, and for some reason around october 27th, all of the twitter accounts with the new, longer ids return this error message:

```
[{u'message': u'Sorry, that page does not exist.', u'code': 34}]
```

these accounts specifically:

```json
[
  { "account": "potus", "id": 822215679726100500},
  { "account": "vp", "id": 818910970567344100},
  { "account": "whitehouse", "id": 822215673812119600},
  { "account": "presssec", "id": 818927131883356200}
]
```

**Comment by fitnr** [comment]
Another workaround might be to use the `id_str`parameter
```
api.user_timeline(user_id='822215679726100500')
```

**Comment by Harmon758** [comment]
You're attempting to pass a screen name as an ID (e.g. 783214).
To pass a screen name instead of a user ID, simply do `api.report_spam(screen_name="twitter")`.
See https://tweepy.readthedocs.io/en/latest/api.html#API.report_spam and:
https://github.com/tweepy/tweepy/blob/1de28d24ec8fce97c3775c0795c97d70ca6d3a5c/tweepy/api.py#L867-L879
@bpb27 This is an unrelated issue. I'm also unable to reproduce this.
You seem to simply be using the wrong user IDs.
The IDs for those accounts are:
```
"potus": 822215679726100480
"vp": 818910970567344128
"whitehouse": 822215673812119553
"pressec": 818927131883356161
```
