### ISSUE TITLE
'Must be authenticated' error when calling rate_limit_status() with app-only authentication.

### ISSUE THREAD

**Issue by githubinator1** [tweepy/tweepy#965]
app_auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
api = tweepy.API(app_auth)
api.rate_limit_status()

"tweepy.error.TweepError: Must be authenticated."

whereas the following will work:

app_auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
api = tweepy.API(app_auth)
statuses = api.statuses_lookup(request_ids)

**Comment by fitnr** [comment]
You've authenticated the application, but not a particular user. Some queries are OK as an application, but others, like getting a rate limit, only make sense when authenticated for a particular user.

See [the docs](http://docs.tweepy.org/en/v3.5.0/getting_started.html#hello-tweepy), in particular the marked line
```python
import tweepy
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret) # <- important
api = tweepy.API(auth)
```

**Comment by githubinator1** [comment]
I disagree with the original premise. The app / user athentication have two
distinct rate limits. See the second row at:

https://developer.twitter.com/en/docs/basics/rate-limits.html

I use this feature extensively in twitter4j.


On Nov 12, 2017, at 7:21 AM, Neil Freeman <notifications@github.com> wrote:

You've authenticated the application, but not a particular user. Some
queries are OK as an application, but others, like getting a rate limit,
only make sense when authenticated for a particular user.

See the docs
<http://docs.tweepy.org/en/v3.5.0/getting_started.html#hello-tweepy>, in
particular the marked line

import tweepy
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret) # <- important
api = tweepy.API(auth)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tweepy/tweepy/issues/965#issuecomment-343744567>, or mute
the thread

**Comment by fitnr** [comment]
You may have found an error in the API, which is returning a 401 response for unauthenticated requests to rate_limit_status:
```
>>> import tweepy
>>> auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
>>> api = tweepy.API(auth)
>>> try:
...     api.rate_limit_status()
... except Exception as e:
...     print(e)
... 
Must be authenticated.
>>> print(e.response)
<Response [401]>
>>> e.response.json()
{'request': '/1.1/application/rate_limit_status.json', 'error': 'Must be authenticated.'}
```

**Comment by githubinator1** [comment]
Interesting. I'll run a few tests in twitter4j and post the results.

**Comment by Harmon758** [comment]
This seems to be either a bug with the endpoint or an error in the documentation.
For now, I've made a forum post about it: https://twittercommunity.com/t/401-unauthorized-response-from-application-rate-limit-status-when-using-application-only-authentication/125182.

**Comment by Harmon758** [comment]
After looking into it further, this is actually an issue with how the authentication is being provided.
It seems that using OAuth 1 for application-only authentication works for most endpoints, but does not work for the [application/rate_limit_status endpoint](https://developer.twitter.com/en/docs/developer-utilities/rate-limit-status/api-reference/get-application-rate_limit_status) that [`API.rate_limit_status`](https://tweepy.readthedocs.io/en/latest/api.html#API.rate_limit_status) uses. Since [the documentation only specifies OAuth 2 for application-only authentication](https://developer.twitter.com/en/docs/basics/authentication/overview/oauth) and using OAuth 1 for it is undocumented, this isn't an issue with Twitter's API (or Tweepy).
Instead, you should use `AppAuthHandler` (which uses OAuth 2) instead of `OAuthHandler` (which uses OAuth1):
https://github.com/tweepy/tweepy/blob/7e1aba026163a024b43a481f68be700eb9cd4f92/tweepy/auth.py#L156-L160 https://github.com/tweepy/tweepy/blob/7e1aba026163a024b43a481f68be700eb9cd4f92/tweepy/auth.py#L32-L35
