### ISSUE TITLE
Unicode error  'charmap' codec can't encode character '\u2019'

### ISSUE THREAD

**Issue by onlymicky** [tweepy/tweepy#966]
Hello !! Hope someone could help me. 

I tried to fetch the public tweets on my personal account. It could return results,but just a few. Then  a UnicodeEncodeError also returned. Is there any superman could tell me how to solve the problem? 

Thank you very much.
![_20171113170320](https://user-images.githubusercontent.com/33632179/32735953-8790af0e-c896-11e7-9f79-71e620acc2f5.png)

**Comment by Harmon758** [comment]
This is an issue with your console's code page/encoding rather than an issue with Tweepy.
You're attempting to print a character outside the range that [CP437](https://en.wikipedia.org/wiki/Code_page_437) supports.
This is easily resolved by changing the active code page to UTF-8 using [`chcp`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/chcp) and specifying [`65001`](https://docs.microsoft.com/en-us/windows/desktop/Intl/code-page-identifiers).
