### ISSUE TITLE
api.user_timeline not grabbing full tweet

### ISSUE THREAD

**Issue by vism2889** [tweepy/tweepy#988]
Hello, 
I am having an issue with not grabbing a full tweet when using the `api.user_timeline` method.  Was wondering if anyone could help me out with it?  Tweepy code is below:

```python
twitter_name = input("Enter a Twitter Handle: ")
for name in twitter_name:
    try:
        stuff = api.user_timeline(screen_name = twitter_name, count = 100, include_rts = False)
    except tweepy.TweepError as e:
        twitter_name = input("The handle you entered was invalid, please try again: ")
    catchcount = 0
```

This returns the tweet followed by '...' then a link.  Ideally I would like to return the full tweet.  Is there a way to do that while still using the `api.user_timeline method`?  Or another method that allows specified tweet count and returns a list of `Status` objects without specifying a tweet ID number? like in the `api.get_status` method with param `tweet_mode = 'extended'` but for returning multiple tweets at a time.

Other info regarding similar issues see: #935 
Much appreciated!!

**Comment by corycomer** [comment]
You can include the `tweet_mode = 'extended'` param with most of the API calls, user_timeline included. 

```python
stuff = api.user_timeline(screen_name = twitter_name, count = 100, include_rts = False, tweet_mode = 'extended')
```

Should return the full tweet. Keep in mind, the response object is slightly different, and you'll want to look for `full_text` instead of just `text`.

**Comment by vism2889** [comment]
@corycomer Thank you! That worked perfectly!

**Comment by kamalikap** [comment]
@corycomer I have the same error persisting even if I use  tweet_mode = 'extended' and change text to full-text. Can you please help?

**Comment by Nahaj** [comment]
i got only 200 tweets how to change it to 1000

**Comment by Harmon758** [comment]
I've added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) to supplement [Twitter’s Tweet updates documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).

@kamalikap What error are you referring to? It's impossible to determine what your issue is without more information, such as a traceback and/or any relevant code. However, when using extended mode, the `text` attribute of the Status object is replaced with a `full_text` attribute, not `full-text`, which would be an invalid attribute name.

@puntofisso When using extended mode, the `text` attribute of the Status object is replaced with a `full_text` attribute.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

@Nahaj That is not related to this issue.

If you're using [`API.user_timeline`](https://tweepy.readthedocs.io/en/latest/api.html#API.user_timeline), the maximum number of Tweets to try and retrieve per distinct request is 200, as specified for the documentation for the `count` parameter of the [GET statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline) that the method uses.

To retrieve more than 200, you'll need to perform multiple requests and iterate through the pages.
Tweepy provides a Cursor to facilitate pagination. See the [Cursor Tutorial documentation](https://tweepy.readthedocs.io/en/latest/cursor_tutorial.html).

**Comment by casseyknp** [comment]
i used tweet_mode="extended" and change the text to full_text, but it still cut off

this is my code:


for tweet in tweepy.Cursor(api.search,q=["netflix"], count=500, lang="id",since="2020-07-9", tweet_mode = 'extended').items(200):
    print  (tweet.created_at, tweet.full_text)
    csvWriter.writerow([tweet.created_at, tweet.full_text.encode('utf-8')])

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues. This is unrelated to this issue.
If the Tweet in question is a Retweet, see https://tweepy.readthedocs.io/en/latest/extended_tweets.html#handling-retweets.

For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
