### ISSUE TITLE
Turning Status object to String?

### ISSUE THREAD

**Issue by Vucko0** [tweepy/tweepy#989]
Really need some help been stuck on this for a couple of days. I have my program working but I'm stuck on one thing. 

My program successfully grabs a tweet that I'm mentioned in and displays it. The problem is that since the tweet is directed at me it contains my Twitter username. For example, "@mytwittername their message" I get that in my output but I need to remove "@mytwittername" from the tweet. To make my reply to make sense.

I've done everything I could find to convert it to a String but had no luck at all. How can I remove my username from there tweet?

Heres my code:
```
tweets = api.search(q="@mytwittername",count=100,include_entities=True)
t = ['@mytwittername', '@MyTwitterName']

for s in tweets:
    sn = s.user.screen_name
    m = "@%s message" % (sn)
    s = api.update_status(m, s.id)
    #print(dir(s))

for result in tweets:
    print (result.text)
```

One of the things I tried, but since I can't make it a String it won't work:
```
for userName in result.text:
    if userName == "@mytwittername":
        result.text.replace("@mytwittername", "")
        print (userName)
    else:
        print("No username")
```

**Comment by vism2889** [comment]
can you post a sample output?

**Comment by Harmon758** [comment]
`Status.text` that you're using is a string.

> ```
> for userName in result.text:
>     if userName == "@mytwittername":
>         result.text.replace("@mytwittername", "")
>         print (userName)
>     else:
>         print("No username")
> ```

This will simply iterate through every character in the text of the Tweet and print "No Username" for each character, since a single character will never `== "@mytwittername"`.

You can simply do something like:
```py
for result in tweets:
    if result.text.startswith("@mytwittername"):
        parsed = result.text[len("@mytwittername"):]
```
Note, this will still have the space after the mention at the beginning of `parsed`.
You can also use `.replace` as you attempted to do if you want to replace it anywhere in the string.
Alternatively, you could use the `in_reply_to_screen_name` attribute of the Status/[Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object.html) or the `screen_name` attribute of the [User object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object) from the `user` attribute of the Status object like you attempted to, in place of "@mytwittername".
