### ISSUE TITLE
update_status with in_reply_to_status doesn't work

### ISSUE THREAD

**Issue by hadaev8** [tweepy/tweepy#994]
Its just send tweet, not comment.
https://stackoverflow.com/a/47159329/8067584
I try advice from this answer, but it doesn't work.
it kust make tweet, not reply.
Code:
try:
	api.update_status(status='@{0} {1}'.format(tweet.user.name, status), in_reply_to_status = tweet.id)
except Exception as e:
	print(e)

**Comment by Harmon758** [comment]
As the [documentation for the statuses/update endpoint](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update), which [`API.update_status`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_status) uses, notes about the `in_reply_to_status_id` parameter:
> This parameter will be ignored unless the author of the Tweet this parameter references is mentioned within the status text. Therefore, you must include `@username` , where `username` is the author of the referenced Tweet, within the update.

However, you're using `tweet.user.name`. Assuming `tweet` is a Status object, then `tweet.user` is a User object, and the `name` attribute of a User object is simply the name that they set (e.g. [@​TwitterDev](https://twitter.com/TwitterDev)'s name is "Twitter Dev"), rather than their screen name/handle/username.
For that, simply use the `screen_name` attribute, e.g. `tweet.user.screen_name`.
See https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
